### ISSUE TITLE
DD-MM-YYYY and MM-DD-YYYY in eventDate

### ISSUE THREAD

**Issue by ramorrismorris** [tdwg/dwc#100]
dwc guidance documents should explicitly recommend against these commonly human-used forms since it is impossible for some dates to distinguish between the U.S. usage MM-DD-YYYY and the European usage DD-MM-YYYY.  A casual misreading of ISO8601 might lead one to (erroneously) believe that these are compliant with ISO8601 and therefore compliant with dwc:eventDate suggestions.

I've seen these forms in published DwC-A in the wild.

**Comment by tucotuco** [comment]
Though these forms are easily found "in the wild", I don't think it is because of ambiguity in the term definition. ISO8601 is quite explicit and does not allows those forms. I would prefer not to muddy the definition with things that are not supposed to happen. I do think there is room for elaboration for all of Darwin Core in auxiliary documents. It is not likely that anyone will be more likely to read those documents any more than they read the definitions now, but there is room for one or more best practice guides, such as Apple Core (https://github.com/tdwg/applecore/tree/master/wiki ?), in which people might be more likely to seek recommendations en masse.

If you still feel strongly about this recommendation, I suggest taking it to tdwg-content as a open discussion forum, which the GitHub issue tracker is not.

For now, marking as wontfix.

**Comment by debpaul** [comment]
Maybe we can pull out some examples to show people OR note this issue in the relevant TDWG DQ flags group where ambiguous dates are found? (IOW, should be ?easy to tell if there are mixed date versions in a dataset? at least a dataset should be consistent MM-DD-YYYY or DD-MM-YYYY - and if so recommendation can be made to change this to YYYY-MM-DD in the future)? I'm guessing this test exists already.

**Comment by tucotuco** [comment]
It doesn't exist that I know of, but great idea. I have added it to the ideas for Kurator.

**Comment by tucotuco** [comment]
The eventDate term does have the recommendation to use ISO 8601:2004(E). This should probably be updated to ISO 8601-1:2019, which should have any practical technical ramifications on existing data.
Part of the confusion about allowed formats comes from the fact that Darwin Core Archive has a dateFormat attribute (see http://rs.tdwg.org/dwc/text/#2-metafile-content) that allows the format to be specified for an entire dataset. The description of that attribute is:

"When verbatim dates are consistent in format, this field can be used to indicate the format represented. It is recommended to use the date, dateTime and time for field formats wherever possible, but where verbatim dates are required, a format may be specified here. This should be considered a ‘hint’ for consumers. It is recommended that consumers support the minimum combinations of DD MM and YYYY with the separators / and -. Examples: DDMMYYYY: for dates of the form 21121978, DD-MM-YYYY: for dates of the form 21-12-1978, MMDDYYYY: for dates of the form 12211978, MM-DD-YYYY: for dates of the form 12-21-1978, YYYYMMDD: for dates of the form 19781221."

Though this may be convenient for some data publishers that have consistency across a whole data set, it is not optimal for records when the participate in the larger body of shared data. Further, and more important, it is supposed to apply to "verbatim dates." I propose that the text guide be amended to make it clear that the dateFormat attribute applies specifically to the term dwc:verbatimDate.

**Comment by MattBlissett** [comment]
> I propose that the text guide be amended to make it clear that the dateFormat attribute applies specifically to the term dwc:verbatimDate.

I think it's fairly clear already. Perhaps just put "verbatim dates" and "It is recommended to use the date, dateTime and time for field formats wherever possible" in bold font?

Looking through the datasets published to GBIF, we have a few hundred with `dateFormat="YYYY-MM-DD"`, and the rest don't have this attribute. No-one who has DD-MM-YYYY or MM-DD-YYYY in verbatim dates has told us so -- but then, we don't yet process this attribute anyway.

**Comment by tucotuco** [comment]
I mention it because @trobertson has mentioned multiple times that this
applies to eventDate, and since he is the author of the document...
I want to make sure it does NOT apply to eventDate, thus avoiding any
contention about the ISO recommedation for that term.
I think it is interesting that no one is using it for any other format than
yyyy-mm-dd.

**Comment by debpaul** [comment]
I’m confused - why would verbatim have a suggested format - if it’s verbatim?

Sent from Shoe (my iPhone)

On Oct 28, 2019, at 1:03 PM, Matt Blissett <notifications@github.com> wrote:

﻿

I propose that the text guide be amended to make it clear that the dateFormat attribute applies specifically to the term dwc:verbatimDate.

I think it's fairly clear already. Perhaps just put "verbatim dates" and "It is recommended to use the date, dateTime and time for field formats wherever possible" in bold font?

Looking through the datasets published to GBIF, we have a few hundred with dateFormat="YYYY-MM-DD", and the rest don't have this attribute. No-one who has DD-MM-YYYY or MM-DD-YYYY in verbatim dates has told us so -- but then, we don't yet process this attribute anyway.

**Comment by tucotuco** [comment]
Very good question. But, it isn't a suggested format. Rather, it is a way;
if they are consistent, to at least be interpreted into an eventDate.

**Comment by debpaul** [comment]
Hm. I would say that if you asked me to use a term called verbatimDate, I would put verbatim data in it. I would find it quite strange if you would suggest I do otherwise. I think you will find the collections community might also find it weird that one would impose a suggested format on a "verbatim" field. If you want to suggest a format, then it's by-definition, not verbatim.
If you want them to put structure so that you can "interpret" into an eventDate, why not instead get them to use eventDate themselves? (but perhaps I'm not understanding this thread).

**Comment by tucotuco** [comment]
@debpaul I think you understand perfectly where this thread has taken us. The explanation of and ultimately the expectation based on the use of the dateFormat in Darwin Core archives is confusing and should be clarified. 
If "verbatim dates" really refers to values in the source's date field mapped to dwc:eventDate, then it is at odds with the recommendation for the standard and the data quality validation test based on that recommendation (https://github.com/tdwg/bdq/issues/66). It would mean that it is fine to share dates in Darwin Core archives in other formats if the format is declared, but they would require transformation if aggregated, because there is no place to declare the date format in a Darwin Core record.
If "verbatim dates" really refers to values in the source's date field mapped to dwc:verbatimEventDate, then there is no inconsistency with any recommendations, no data quality validation test wold fail, and in the case where all dates mapped in this way had the same format (might be a fairly rare situation), one could interpret them to ISO 8601 and populate dwc:eventDate as well.
Would like to hear opinion from @timrobertson100.

**Comment by debpaul** [comment]
I get very well that MM-DD or DD-MM pose an unsolvable date issue. So I would hope that we can figure out multiple ways to (require? inspire) enforce YYYY-MM-DD in eventDate. I'm assuming though, that dwc:verbatimEventDate remains "verbatim" (as in "Spring", or "Feb. 1"). If someone in the above thread is really suggesting some sort of _suggested format_ for a **"verbatim"** field, I might have to suggest we rename the field "pseudoVerbatim"

**Comment by tucotuco** [comment]
No one is suggesting a suggested format, only a post-facto format hint to
let interpret the content.

**Comment by tucotuco** [comment]
> The eventDate term does have the recommendation to use ISO 8601:2004(E). This should probably be updated to ISO 8601-1:2019, which should have any practical technical ramifications on existing data.

This has been done.

> Part of the confusion about allowed formats comes from the fact that Darwin Core Archive has a dateFormat attribute (see http://rs.tdwg.org/dwc/text/#2-metafile-content) that allows the format to be specified for an entire dataset. The description of that attribute is:

Consensus seems to be that the documentation is fairly clear on the use of the dateFormat attribute in a Darwin Core archive, and that it isn't really being used much anyway. Marking as dismissed and closing.
