### ISSUE TITLE
Report of broken link

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#103]
Eduardo Rudas (SIBBR) reported a broken link on the DwC website via email to @pmergen:

> I want to report a broken link in the page http://rs.tdwg.org/dwc/terms/
> http://rs.tdwg.org/dwc/2014-11-08/terms/index.htm is not working, that is, the older page of the terms.

Is this related to the half-finished migration to the new DwC website? What is stopping us from pulling in the new website stuff we did in January?

**Comment by mdoering** [comment]
rs.gbif.org has not been migrated, but this appears to be an issue of migrating dwc from google code to github. The link should resolve to somewhere on github pages, but its not there: https://github.com/tdwg/dwc/tree/gh-pages

Maybe we can focus on getting the cleaned up dwc branch live?
What are real show stoppers?
https://github.com/tdwg/dwc/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Migration+of+DwC+to+GitHub%22

**Comment by peterdesmet** [comment]
Real stopper for me currently is time. Can only work on this in October.

**Comment by tucotuco** [comment]
This problem exists for every page on http://rs.tdwg.org/dwc/, because the versions used to be saved in distinct directories off of that root when they became outdated. Those were removed to releases under revision, and there is no way to access the distinct pages by URL within a release, which is an archive of the site in a given state. I know no other way to restore the previous functionality without restoring the version directories. An alternative is to abandon the page versioning and keep only releases from now on. I would rather not go back through previous version and relink them to releases that did not exist at the time they were made. Any other ideas?

**Comment by peterdesmet** [comment]
In that case we should remove that link and describe where previous versions can be accessed. Seems like the term history is still available (e.g. http://rs.tdwg.org/dwc/terms/history/index.htm#georeferenceVerificationStatus-2009-04-24) though, which is good?

**Comment by tucotuco** [comment]
This problem no longer exists following the site reorganization. Previous version tracking will be accomplishing through commits to the repository rather than explicit page versioning and archiving.
