### ISSUE TITLE
Publish new Darwin Core website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#106]
@mdoering @tucotuco: I'd like to know what is blocking us from publishing the new Darwin Core website. The bulk of the work (simplifying the repo structure and using a simple Bootstrap style for the website) was done at our January hackathon in the `dwc_cleanup` branch, but nothing has happened since. What blocking issues remain (technical and social, reported or new)?

**Comment by mdoering** [comment]
I dont know Peter. I remember we changed the actual reference rdf file and that needed to be accepted by tdwg before we can publish the site. Has that happened?

**Comment by peterdesmet** [comment]
@tucotuco do you know? Do we need a @tdwg/exec decision or is this blocked somewhere else?

**Comment by tucotuco** [comment]
I don't think we finished the work, actually. As in issue #103, the milestone Migration of DwC to GitHub has open issues. 

https://github.com/tdwg/dwc/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Migration+of+DwC+to+GitHub%22 

Once everything is done and the site is ready, under current process there really is no precedent for how to make this change. As such, I think it is fine to ask the Exec if we can proceed to do the change over, or what we need to do in order to be able to. Muddy water.

**Comment by peterdesmet** [comment]
When do we plan to work on the [Migration of DwC to GitHub](https://github.com/tdwg/dwc/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Migration+of+DwC+to+GitHub%22) milestone? Might work best if we work on this at the same time? Maybe same location again?

**Comment by tucotuco** [comment]
I REALLY like the idea. I do not know how I will find time to concentrate on it otherwise, truthfully.

**Comment by mdoering** [comment]
I like that idea too. I just remember that the main stopper to go live with the new branch was the needed executive decision to change the normative file. Is that still the case? And should we first try to document clearly what still needs to be done?

**Comment by baskaufs** [comment]
I'm not really up on this thread, so I don't know what changes have yet to be incorporated in the next release, but I just wanted to point out the pending pull request that I made in April in order to fix Issues #111 and #112. I was under the impression that there would not be any approval required to incorporate those changes, since they were really corrections of errors in the linking of versions as opposed to changes that would affect the meaning of any terms.  If there is an impending new release, it would be good to get those fixes incorporated before it's releases.

**Comment by peterdesmet** [comment]
I think it would be good to document a roadmap of what still needs to be done, for the executive and also for us, as I lost track a bit. That something we can actually do in the milestone description: https://github.com/tdwg/dwc/milestone/1 + GitHub now also allows to order issues in a milestone, so that should help to. Who's up for documenting the roadmap?

**Comment by peterdesmet** [comment]
With all the work been done in https://github.com/tdwg/dwc/milestone/4 there are no more ratification/exec decisions blocking this.

The only thing blocking us from pushing this to `gh-pages` is that a lot of URLs to the current website will break if we do this, as the new website consists of just a single page: https://github.com/tdwg/dwc/tree/master/www/guides. We need to redirect those first. I'll update #72 with all the links that need to be redirected.

**Comment by baskaufs** [comment]
@mdoering @peterdesmet @tucotuco @stijnvanhoey  OK, I want to report some progress on generating the myriad of human-readable pages that the Standards Documentation Specification says we should have.  I've been working on the [server script](https://github.com/tdwg/rs.tdwg.org/blob/master/html/restxq.xqm) and HTML page templates that would be necessary to generate the HTML pages for stuff like term lists, vocabularies, and versions of term lists, vocabularies, and the terms themselves.  I have made no attempt to do any kind of styling - just to get the content right.  

The HTML is generated from the same data used to generate the various Linked Data serializations (JSON-LD, RDF/XML, and RDF/Turtle); that is, the data in the https://github.com/tdwg/rs.tdwg.org repo.  So when those data are updated and get dumped into the server database, everything gets updated at once since all of the representations are generated dynamically.  For anyone who is interested in the gory details, the templates for all of the various HTML pages is at https://github.com/tdwg/rs.tdwg.org/blob/master/html/html.xqm .  So cosmetic changes in page appearance and formatting can be made just by updating that template. 

Right now, this is running on the Vanderbilt Semantic Web Working Group's BaseX cloud server at https://sparql.vanderbilt.edu/gom/ (despite the subdomain name, it's not a SPARQL endpoint).  So to test how the dereferencing works, take any TDWG vocabulary-related URI that starts with "http://rs.tdwg.org/" and replace the http://rs.tdwg.org/ with https://sparql.vanderbilt.edu/gom/.  For example, to dereference the obsolete Darwin Core term http://rs.tdwg.org/dwc/curatorial/CollectorNumber, dereference https://sparql.vanderbilt.edu/gom/dwc/curatorial/CollectorNumber.  

Here is an example of a term list:
https://sparql.vanderbilt.edu/gom/dwc/iri/ (for http://rs.tdwg.org/dwc/iri/),  

Here is an example of a vocabulary:
https://sparql.vanderbilt.edu/gom/dwclink/ (for http://rs.tdwg.org/dwclink/)

Here is an example of a term version:
https://sparql.vanderbilt.edu/gom/dwc/iri/version/disposition-2015-03-27 (for http://rs.tdwg.org/dwc/iri/version/disposition-2015-03-27)

Here is an example of a term list version:
https://sparql.vanderbilt.edu/gom/dwc/version/terms/2009-09-11 (for http://rs.tdwg.org/dwc/version/terms/2009-09-11)

etc.  The server script is set up for Darwin Core and Audubon Core term IRIs to dereference to the appropriate spot in the Quick Reference Guide (e.g. https://sparql.vanderbilt.edu/gom/dwc/terms/recordedBy) and the Audubon Core Term List document (e.g. https://sparql.vanderbilt.edu/gom/ac/terms/caption), so the current dereferencing behavior would be retained, at least for now.  

As before, the server does content-negotiation, so if you request one of the other content-types (application/rdf+xml, text/turtle, application/json) instead of the text/html that a browser will ask for, you'll get the appropriate serialization.  You can test this out with cURL or Postman.  

I still have a lot of work to do on dealing with documents that are part of standards and also putting together a database of contributors so that they can be linked to the standards parts that they contributed to.  There are also some issues about http: vs. https: and what to do about http://rs.tdwg.org/dwc/terms/, which currently dereferences to the quick reference guide, but technically by the SDS should dereference to a term list.  

Anyway, whenever we can make progress on getting a TDWG-specific BaseX server instance running, we can work towards the point of "flipping the switch" and actually making the http://rs.tdwg.org/ IRIs dereference.  At that point the various hyperlinks in the documents would actually work (for convenience, I made them absolute links rather than relative).  For now I can keep the script running on the Vanderbilt cloud server, but eventually it will have to go away, since we need to be able to use it for other purposes.

**Comment by mdoering** [comment]
Thanks Steve, @MattBlissett and @timrobertson100 need to be involved to setup a new server at GBIF
