### ISSUE TITLE
Versioning darwin core

### ISSUE THREAD

**Issue by dvdscripter** [tdwg/dwc#107]
Hi,

I'm not sure if DWC standard enforce use of xml but when generating meta.xml (at IPT) no version of DWC is available at any place.

http://rs.tdwg.org/dwc/terms/ shows version as date but the replaced versions is returning 404, two members of SiBBr reported this broken link and no one is answering for months.

Can you place any validation like eml?

```
xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1
```

For developers trying to write indexers or custom validators you basically lost in which version of DWC the resource is made.

**Comment by cgendreau** [comment]
I think there is 2 different things here:
 - The broken link for the page: http://rs.tdwg.org/dwc/2014-11-08/terms/
 - The fact that the namespace in the meta.xml file doesn't include the version
`<archive xmlns="http://rs.tdwg.org/dwc/text/" ...­>`

**Comment by dvdscripter** [comment]
Sure, sorry to overload this issue with two problems but seems noone of TDWG reply in contact e-mail.

**Comment by peterdesmet** [comment]
Hi @dvdscripter, sorry for the late response. I'm a (recent) contributor to Darwin Core and was not aware that versions were kept at e.g. http://rs.tdwg.org/dwc/2014-11-08/terms/ We recently automated the process of generating the DwC website on a new release and that's maybe something we overlooked. In case it helps your specific problem, all versions of Darwin Core are kept as releases on GitHub: https://github.com/tdwg/dwc/releases

@tucotuco @mdoering @timrobertson100 can you chime in? Things to solve:

* [ ] I knew that single terms were accessible at e.g. http://rs.tdwg.org/dwc/terms/history/index.htm#acceptedScientificName-2009-07-06, but was not aware we also had endpoints for the whole standard (in addition to the releases). Is this something we want to maintain/fix? If not, the `replaces` link should be removed.
* [ ] I notice the most recent version listed at the top of http://rs.tdwg.org/dwc/terms/, yet there is no release of that: https://github.com/tdwg/dwc/releases
* [ ] Version in meta.xml file...

**Comment by tigreped** [comment]
I was talking to @dvdscripter since we work together on SiBBr, I hope everyone understands that having the DwC version information as part of the DwC-A metadata is important because it allows proper mapping of terms according to the DwC version at the time of the publishing of the resource on the IPT regardless of the version.

Currently, the only way to do that would be fetching the list of terms used in a given DwC-A after parsing the meta.xml file, and then checking this set of fields against all available version descriptions available, but I'm sure everyone here understands this is not elegant.

Since you are just arriving around here, @peterdesmet , allow me to explain: I'm responsible for the development of [SiBBr's data portal](gbif.sibbr.gov.br/explorador) and we arrived in this problem when we realized that on the last DwC version the field **rights** had been renamed to **licence**. We would need an elegant way of "normalizing" these differences over the different DwC versions used by different DwC-A's we might have to index from a very heterogeneous environment of IPTs.

It might seem trivial to manage from the previous version to the latest one, but when we think about managing IPTs and DwC-As with several different versions it causes direct impact on database schemas and implementations.

Keeping this infrastructure in sync with current, past and future changes in the standard seems like a valid concern that needs a good solution, in our opinion. So, we thought that adding the DwC version as a metadata of the DwC-A might be a good start, as a simple mechanism to allow proper version management.

**Comment by peterdesmet** [comment]
Yep, I fully understand why knowing the version is a huge advantage when aggregating across many IPTs! @cgendreau and I didn't run into that problem at the early stages of setting up the Canadensys explorer, but I can understand it's getting to be an issue now.

And if I understand correctly, the versions you want listed in the `meta.xml` are not necessarily Darwin Core versions (i.e. linked to the [releases](https://github.com/tdwg/dwc/releases)), but actually releases of the cores and extensions. E.g. `occurrence core v1.0` or `measurementOrFacts extension v1.2`. That then becomes more of an implementation issue, rather than a standard issue.

I notice http://rs.gbif.org/core/ lists 1 dated version of the occurrence core (don't know who created this), but as http://rs.gbif.org/core/dwc_occurrence_2015-07-02.xml instead of the more logical http://rs.gbif.org/core/2015-07-02/dwc_occurrence.xml (cf. http://rs.gbif.org/extension/gbif/1.0/multimedia.xml).

@timrobertson100 @tucotuco @mdoering I know there were talks about versioning Darwin Core. Were those talks about versioning the core and extensions? If so, what stops us from implementing this as http://rs.gbif.org/core/yyyy-mm-dd/dwc_occurrence.xml or http://rs.gbif.org/core/x.x/dwc_occurrence.xml (and listing this in `meta.xml`)?

**Comment by baskaufs** [comment]
Just to chime in on this discussion: in September I was attempting to put together a draft of a new Standards Documentation Standard as part of the output of the Vocabulary Maintenance Specification Task Group.  I stalled out on this due to getting busy with the start of the fall semester.  However, a significant part of the draft is already there at https://github.com/tdwg/vocab/blob/master/documentation-specification.md .  

In writing the draft, I essentially tried to capture the precedent/current practice of Darwin Core with respect to versions.  That is, we currently seem to have dated versions of all of the terms and we effectively have versions of the vocabulary itself in that the documents get updated on particular dates after there is a new decision about changing the vocabulary.  The draft document really tries to define the various entities that seem to exist (vocabularies, terms, versions, representations, and to nail down how their metadata should be documented and the relationships between various entities should be described, i.e. that a term is part of a vocabulary, that a version is related to earlier or later versions, etc.  

What I am trying to aim for here is not so much to prescribe what should be done, but rather to describe clearly the practice that we do (or want to) follow.  So I would appreciate feedback on the document, such as it is.  It doesn't really differentiate between "versions" and "releases".  Should it?  I'm totally open to advice on this.

**Comment by erudas-SiBBr** [comment]
Hi, I'm working at SiBBr too with @dvdscripter and  @tigreped and I wish to join this interesting discussion. @peterdesmet, I think we are facing a more complex scenario.

As I see it, the cores used by the IPT is a way to group and implement the Darwin Core terms, thus each one could have its own version., so I'm going to call them IPT Cores.

Suppose the first IPT Occurrence Core doesn’t include all the Darwin Core terms, then was decided to include more terms, so the IPT Core version changed and the Darwin Core version remains the same. But what if later the DarwinCore is updated? That means the Darwin Core version changes and the IPT Cores versions remain the same and pointing to the old Darwin Core version, until is decided to update them to comply with the new Dawin Core version.

Given that,  we don't only need to document the IPT Core version, but the Darwin Core version too, so we can know from which Darwin Core version we took the terms to build the IPT Cores.

The document @baskaufs shows to us, is fundamental to addressing this issue.

**Comment by tucotuco** [comment]
> http://rs.tdwg.org/dwc/terms/ shows version as date but the replaced versions is returning 404, two members of SiBBr reported this broken link and no one is answering for months.

This has been fixed.

The suggestion to modify the Darwin Core text standard so that the meta.xml file contains Darwin Core version information is fraught with issues. The biggest one I can think of is that there would be that there would be no way for GBIF to comply when they create Darwin Core archives for download. The content would be an untraceable combination of Darwin Core versions, unless that information was captured on a row-by-type basis. 

Worse still, making the Darwin Core version a requirement would immediately invalidate every Darwin Core archive in existence. Not good.

The Darwin Core terms, releases, and Text delivery mechanism were all designed to function on the latest versions and to maintain the dependency history to have a way to solve what seems to be the main issue represented here, which is to know what to map a term to when that term gets deprecated.

I don't think there is any reasonable action that can be taken on this proposal as it stands. If there really is an open need that can not be solved by traversing the term history, which is already part of the standard, then please make a complete and concrete proposal for a solution.

**Comment by tucotuco** [comment]
Apparent lack of sustained demand. Closing.

**Comment by baskaufs** [comment]
I just wanted to note here for the record that the Darwin Core standard and its component vocabularies, term lists, and terms are actually all versioned and available in machine readable and tabular form. For more information, see the README.md page at <https://github.com/tdwg/rs.tdwg.org>. 

Similarly, there is now a process in place for generating a GitHub release of all TDWG standards metadata each time changes are made to a standard. See <https://github.com/tdwg/rs.tdwg.org/releases> for the list of releases.

This is not what was asked for here with respect to the `meta.xml` file, but it is possible to unambiguously identify any part of a TDWG standard using an IRI.
