### ISSUE TITLE
Should previousIdentifications be part of Identification?

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#109]
Should the term dwc:previousIdentifications not be under the class Identification? It is currently lsited under Organism

**Comment by baskaufs** [comment]
It seems that generally property terms are listed under the class of the kind of thing that would have that property.  Since organisms would have identifications, I think that's why dwc:previousIdentifications are listed under dwc:Organism.  I'm not sure that there is consistency on this for every property term, but I think it's what happens most of the time when it seems clear what the class is of the subject resource.

**Comment by tucotuco** [comment]
I agree with Steve. Sure, previousIdentifications have something to do with Identifications, but the dwcattributes:organizedIn attribute of a term is meant to indicate that the term would be a reasonable candidate to be property of that Class, if we went as far as creating an ontology with such relationships. Specifically, I would ask the question, "Would a previousIdentification be a property of an Identification?" To me the answer is a clear, "No".

**Comment by mdoering** [comment]
I agree. I was simply misled by the name of the term that it should belong to the identification class.
