### ISSUE TITLE
hasVersion incorrect in RDF documents

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#112]
Based on observations by Steve Baskauf with respect to the hasVersion attribute of Darwin Core terms in RDF, I have made the following observations.

The hasVersion information is incorrect throughout both dwctermshistory.rdf and dwcterms.rdf. The terms all have hasVersion populated by URLs with fragment identifiers that serve to link to the right place in the HTML documentation, but do not contain an actual identifier for a version. In fact, the term version is in identifier for the term itself. There is only ever one version of a term (currently), and that is identified in the rdf:Description. For example, the following identifies a no longer current version of the Darwin Core genus term. 

`<rdf:Description rdf:about="http://rs.tdwg.org/dwc/terms/genus-2009-04-24">`

Any functional or semantic change in the term results in the creation of a new term, which would be related to the previous one with dcterms:replaces. Thus,

`<rdf:Description rdf:about="http://rs.tdwg.org/dwc/terms/genus-2009-08-24">`
  `<dcterms:replaces rdf:resource="http://rs.tdwg.org/dwc/terms/genus-2009-04-24"/>`

And since the replacement mechanism, using distinct terms each time there is a semantic change, is the versioning mechanism, the hasVersion attribute of each term would have to just reference the term itself, which seems like redundant clutter. 

Since they are all incorrect, no one could have possibly used them effectively to date,  and apparently no one has even tried. I propose to remove all hasVersion tags from dwctermshistory.rdf and dwcterms.rdf. And since it is not semantically or functional relevant, I propose that this can be done as "Minor editorial errata" under 3.1 of the Darwin Core namespace policy. I'll give this a week or so for commentary here, and if there are no objections, will make the changes throughout the documentation.

**Comment by baskaufs** [comment]
I created a fix for this problem by loading the dwctermshistory.rdf file into my local triplestore and then running the following query: 

```
# Remove the dcterms:hasVersion triples (5769 triples = 6353-584):
CONSTRUCT {?s ?p ?o} WHERE {
  ?s ?p ?o.
  MINUS {?s dcterms:hasVersion ?o}
  }
```

I counted the number of triples before (6353) and after (5769) and the difference (584) was the same as the number of terms that I counted (584), which should be the case if the one dcterms:hasVersion triple was removed for each term.  I visually examined the file and this seems to be a fix.

I have generated a replacement file for dwctermshistory.rdf that includes this fix as well as the fix for Issue #111 .  I can either email it to John or try to do a pull request.

**Comment by baskaufs** [comment]
OK, I've looked at the dwcterms.rdf situation now.  I'm going to propose a solution that is slightly different than what John suggested in the original issue description.  For dwctermshistory.rdf, I agree that it makes sense to remove all of the dcterms:hasVersion triples.  As I perceive the terms in dwctermshistory, they ARE all of the versions of Darwin Core terms, so it doesn't really make sense to say that the versions have versions.

However, in the case of dwcterms.rdf, I think that it is critical that some dcterms:hasVersion triples remain.  dcterms:hasVersion is the link from the current generic term (e.g. dwc:recordedBy) to it's dated version (e.g. dwc:recordedBy-2014-10-23) and we don't want that link to go away.  Yes, there is sometimes a dcterms:replaces link to the version that the current term replaces, but not every term has an earlier version.  In such a case, if all of the dwc:hasVersion links go away, there is no connection between a current term in dwcterms.rdf and any version of it in dwctermshistory.rdf .

I propose that the fix for dwcterms.rdf is to fix the dwc:hasVersion links so that they point to the correct URI of the most recent version in dwctermshistory.rdf .  Then delete all of the dwc:replaces triples from dwcterms.rdf .  They aren't needed if there is a link from the current term in dwcterms.rdf to the current version in dwctermshistory.rdf because the current version is linked to the previous version in dwctermshistory.rdf (or at least it is after applying the repairs I described earlier).  

Here is the current situation (showing only the relevant triples):

In dwcterms.rdf:
```
dwc:recordedBy
     dcterms:hasVersion <http://rs.tdwg.org/dwc/terms/history/#recordedBy-2014-10-23>;
     dcterms:replaces dwc:recordedBy-2009-04-24.
```

In the repaired dwctermshistory.rdf:
```
dwc:recordedBy-2014-10-23  dcterms:replaces dwc:recordedBy-2009-04-24.
dwc:recordedBy-2009-04-24 dcterms:replaces <http://rs.tdwg.org/dwc/dwcore/Collector-2007-04-17>.
```

Here is how I am proposing it should be:

In the repaired dwcterms.rdf:
```
dwc:recordedBy dcterms:hasVersion dwc:recordedBy-2014-10-23.
```

In the repaired dwctermshistory.rdf:
```
dwc:recordedBy-2014-10-23  dcterms:replaces dwc:recordedBy-2009-04-24.
dwc:recordedBy-2009-04-24 dcterms:replaces <http://rs.tdwg.org/dwc/dwcore/Collector-2007-04-17>.
```

If the repairs are made as I have suggested, it then becomes a simple matter to construct a query to find any version of a current term.  For example, if the repaired dwcterms.rdf and dwctermshistory.rdf files are loaded into a triplestore, the SPARQL query:
```
SELECT DISTINCT ?version ?modDate ?status ?dfn WHERE {
  dwc:recordedBy dcterms:hasVersion ?curVersion.
  ?curVersion dcterms:replaces* ?version.
  ?version dcterms:modified ?modDate.
  ?version rdfs:comment ?dfn.
  ?version dwcattributes:status ?status.
  }
ORDER BY DESC(?modDate)
```
will display all of the versions of dwc:recordedBy and give their modified date, status, and definition.  Doing this sort of query would be much more difficult if all of the dcterms:hasVersion triples were removed from dwcterms.rdf.  

I've loaded the repaired versions of dwcterms.rdf and dwctermshistory.rdf into our endpoint at Vanderbilt: http://rdf.library.vanderbilt.edu/sparql?view and you can try running the query above to see that it works.  Try changing the term to dwc:genus, which has a longer and more intersting history.

For reference, here are the queries I used to fix dwcterms.rdf:

I loaded the triples from dwcterms.rdf as the graph <http://dwcterms> 
and the triples from the repaired dwctermshistory.rdf as the graph <http://dwctermshistory>
```
# List all of the terms in dwcterms.rdf to find out how many there are:
SELECT DISTINCT ?term WHERE {
GRAPH <http://dwcterms> {
  ?term dwcattributes:status ?value.
      }
  }
ORDER BY ?term
# There are 192

# For each of the 192 current terms, find the term version whose local name (after the "/") matches
# the local name (after the #) of the dcterms:hasVersion object:
SELECT DISTINCT ?s ?subjectUri WHERE {
  
  GRAPH <http://dwcterms> {
    ?s dcterms:hasVersion ?objectUri.
         }
  
  GRAPH <http://dwctermshistory> {
    ?subjectUri ?p ?o.
         }
  
  BIND(REPLACE(str(?subjectUri), '^.*(/)', "") AS ?subjectLocalName)
  BIND(REPLACE(str(?objectUri), '^.*(#)', "") AS ?objectLocalName)
  FILTER(?subjectLocalName=?objectLocalName)
  }
# It finds 192

# Construct the corrected dcterms:hasVersion triples:
CONSTRUCT {?s dcterms:hasVersion ?subjectUri} WHERE {
SELECT DISTINCT ?s ?subjectUri WHERE {
  GRAPH <http://dwcterms> {
    ?s dcterms:hasVersion ?objectUri.
         }
  GRAPH <http://dwctermshistory> {
    ?subjectUri ?p ?o.
         }
  BIND(REPLACE(str(?subjectUri), '^.*(/)', "") AS ?subjectLocalName)
  BIND(REPLACE(str(?objectUri), '^.*(#)', "") AS ?objectLocalName)
  FILTER(?subjectLocalName=?objectLocalName)
        }
  ORDER BY LCASE(?subjectLocalName)
  }
# For some reason, it repeats dwc:acceptedNameUsage twice and produces 193 results ???
# I deleted the extra triple

# DROP ALL, then reload only dwcterms.rdf .  Clean out all of the dcterms:hasVersion and dcterms:replaces triples:
CONSTRUCT {?s ?p ?o} WHERE {
  ?s ?p ?o.
MINUS {
  ?s1 dcterms:replaces|dcterms:hasVersion ?o.
      }
  }

# Save the output, then load the cleaned dwcterms.rdf and the repaired dcterms:hasVersion triples
# Output the repaired graph so that it can be saved in a single file (sorted by LCASE of local name):
CONSTRUCT {?s ?p ?o} WHERE {
  ?s ?p ?o.
  BIND(LCASE(REPLACE(str(?s), '^.*(/)', "")) AS ?localName)
  }
Order by ?localName
```

**Comment by tucotuco** [comment]
I agree that the proposed changes remove the unnecessary clutter from dwctermshistory.rdf and maintain the essential and originally intended links of the recommended terms to their histories in dwcterms.rdf.

@baskaufs Could you run your queries to create updated versions of these files based on the two rdf documents as of the latest commit and either send them to me or push them and create a pull request? Then do a separate commit for the proposed fixes in Issue #111 ?

**Comment by baskaufs** [comment]
@tucotuco Assuming I did the pull request right, I created a pull request with the dwcterms.rdf and dwctermshistory.rdf files that I modified as described in this issue and Issue #111.  I'm not sure about how to accomplish a separate commit for the two issues.  This issue involves fixing both files, and #111 applies only to dwctermshistory.rdf .  I guess I don't really understand the process of separating it into two commits, but I don't have write access to the dwc repo anyway, so maybe you can just do it.

**Comment by tucotuco** [comment]
With the new management of term versions, this issue is no longer a problem.
