### ISSUE TITLE
Change term: footprintSRS

### ISSUE THREAD

**Issue by kbraak** [tdwg/dwc#122]
## Change term

* Term identifier (URL of the term to change): http://rs.tdwg.org/dwc/terms/#footprintSRS
* Justification (why is this change necessary?): currently footprintSRS must be provided using the Well-Known Text (WKT) representation of the Spatial Reference System (SRS) for the footprintWKT. This representation is very long (e.g. ESRI WKT for EPSG:28992), thus making it more prone to being written with error compared to writing the shorter EPSG code. For example, publishers might try to provide the Human-Readable OGC WKT using newline characters which can break tabular data. Furthermore, confusion can arise when deciding to use the OGC WKT or ESRI WKT representation. For all these reasons, allowing the SRS for the footprintWKT to also be provided using the EPSG code (assuming it is present in http://epsg.io) will make it easier for publishers to fill in footprintSRS, and for users of the data to understand it.
* Submitter: Kyle Braak

I suggest the following changes (leave blank whatever would not change):

* Term name (in lowerCamelCase): footprintSRS
* Class (e.g. Location, Taxon): Location
* Definition of the term: **The ellipsoid, geodetic datum, or spatial reference system (SRS) upon which the geometry given in footprintWKT is based.**
* Usage comments (recommendations regarding content, etc.): **Recommended best practice is to use the EPSG code of the SRS, if known. Otherwise use a controlled vocabulary for the name or code of the geodetic datum, if known. Otherwise use a controlled vocabulary for the name or code of the ellipsoid, if known. If none of these is known, use the value `unknown`. It is also permitted to provide the SRS in Well-Known-Text, especially if no EPSG code provides the necessary values for the attributes of the SRS. Do not use this term to describe the SRS of the decimalLatitude and decimalLongitude, nor of any verbatim coordinates - use the geodeticDatum and verbatimSRS instead.** 
* Examples: **`epsg:4326`**, `GEOGCS["GCS_WGS_1984", DATUM["D_WGS_1984", SPHEROID["WGS_1984",6378137,298.257223563]], PRIMEM["Greenwich",0], UNIT["Degree",0.0174532925199433]]` (WKT for the standard WGS84 Spatial Reference System EPSG:4326)
* Refines (identifier of the broader term this term refines, if applicable):
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/footprintSRS-2018-09-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable): not in ABCD

Original comment:
**Term name**: [footprintSRS](http://rs.tdwg.org/dwc/terms/#footprintSRS)

**Term change recommendation**: to allow footprintSRS _to also be_ provided using the EPSG code as a controlled vocabulary (e.g. "EPSG:4326").

**Term change justification**: currently footprintSRS must be provided using the Well-Known Text (WKT) representation of the Spatial Reference System (SRS) for the footprintWKT. This representation is very long (e.g. [ESRI WKT for EPSG:28992](http://spatialreference.org/ref/epsg/amersfoort-rd-new/esriwkt/)), thus making it more prone to being written with error compared to writing the shorter EPSG code. For example, publishers might try to provide the [Human-Readable OGC WKT](http://spatialreference.org/ref/epsg/wgs-84/prettywkt/) using newline characters which can break tabular data. Furthermore, confusion can arise when deciding to use the [OGC WKT](http://spatialreference.org/ref/epsg/wgs-84/ogcwkt/) or [ESRI WKT](http://spatialreference.org/ref/epsg/wgs-84/esriwkt/) representation. For all these reasons, allowing the SRS for the footprintWKT to also be provided using the EPSG code (assuming it is present in http://epsg.io) will make it easier for publishers to fill in footprintSRS, and for users of the data to understand it.

**Comment by qgroom** [comment]
Hi Kyle,
it makes sense to me.
Looking back at DwC file I created last year, this is exactly what I have
done without realizing that it was against the standard's recommendation.
Regards
Quentin



Dr. Quentin Groom
(Botany and Information Technology)

Botanic Garden Meise
Domein van Bouchout
B-1860 Meise
Belgium

ORCID: 0000-0002-0596-5376 <http://orcid.org/0000-0002-0596-5376>

Landline; +32 (0) 226 009 20 ext. 364
FAX:      +32 (0) 226 009 45

E-mail:     quentin.groom@plantentuinmeise.be
Skype name: qgroom
Website:    www.botanicgarden.be

**Comment by cgendreau** [comment]
[verbatimSRS](http://rs.tdwg.org/dwc/terms/index.htm#verbatimSRS) and [geodeticDatum](http://rs.tdwg.org/dwc/terms/index.htm#geodeticDatum) include the sentence

> Recommended best practice is use the EPSG code as a controlled vocabulary to provide an SRS, if known.

I think it would make sense to have it as part of the`footprintSRS` definition. The Well-Known Text (WKT) should still be used for cases when it can not be represented by a known EPSG code.

**Comment by tucotuco** [comment]
This would make all the Coordinate Reference System terms consistent and makes good sense to me. If we still allow a WKT representation in the recommendations in the comments it would not adversely affect any published data.

**Comment by tucotuco** [comment]
Here is an official term change request.

## Change term

* Term identifier (URL of the term to change): http://rs.tdwg.org/dwc/terms/#footprintSRS
* Justification (why is this change necessary?): currently footprintSRS must be provided using the Well-Known Text (WKT) representation of the Spatial Reference System (SRS) for the footprintWKT. This representation is very long (e.g. ESRI WKT for EPSG:28992), thus making it more prone to being written with error compared to writing the shorter EPSG code. For example, publishers might try to provide the Human-Readable OGC WKT using newline characters which can break tabular data. Furthermore, confusion can arise when deciding to use the OGC WKT or ESRI WKT representation. For all these reasons, allowing the SRS for the footprintWKT to also be provided using the EPSG code (assuming it is present in http://epsg.io) will make it easier for publishers to fill in footprintSRS, and for users of the data to understand it.
* Submitter: Kyle Braak

I suggest the following changes (leave blank whatever would not change):

* Term name (in lowerCamelCase): footprintSRS
* Class (e.g. Location, Taxon): Location
* Definition of the term: The ellipsoid, geodetic datum, or spatial reference system (SRS) upon which the geometry given in footprintWKT is based.
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use the EPSG code of the SRS, if known. Otherwise use a controlled vocabulary for the name or code of the geodetic datum, if known. Otherwise use a controlled vocabulary for the name or code of the ellipsoid, if known. If none of these is known, use the value unknown. It is also permitted to provide the SRS in Well-Known-Text, especially if no EPSG code provides the necessary values for the attributes of the SRS. Do not use this term to describe the SRS of the decimalLatitude and decimalLongitude, nor of any verbatim coordinates - use the geodeticDatum and verbatimSRS instead. 
* Examples: `epsg:4326`, `GEOGCS["GCS_WGS_1984", DATUM["D_WGS_1984", SPHEROID["WGS_1984",6378137,298.257223563]], PRIMEM["Greenwich",0], UNIT["Degree",0.0174532925199433]]` (WKT for the standard WGS84 Spatial Reference System EPSG:4326)
* Refines (identifier of the broader term this term refines, if applicable):
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/footprintSRS-2018-09-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable): not in ABCD

**Comment by ArthurChapman** [comment]
@tucotuco I fully support this change and it brings it in line with Best Practice which is always a good thing.

**Comment by baskaufs** [comment]
This term does have a `dwciri:` analog. So I think the appropriate thing to do would be to change its definition to match the one given here. The usage comments given above are all about what text string to use as a value. Since the `dwciri:` analog expects an IRI instead of a string, those comments are not relevant, so no comments need to be added for the IRI analog.

**Comment by afuchs1** [comment]
The Australasian Herbarium Information Systems Committee (HISCOM) endorses the proposal.

**Comment by EstebanMH-SiB** [comment]
We endorse this proposal on behalf of @SiBColombia

**Comment by tucotuco** [comment]
Done.
