### ISSUE TITLE
How to map terms with `anyIdentifier` to DwC classes via schema files

### ISSUE THREAD

**Issue by nickdos** [tdwg/dwc#139]
The current web version of DwC terms shows that `taxonID` has a class of `http://rs.tdwg.org/dwc/terms/Taxon`:

http://rs.tdwg.org/dwc/terms/#taxonID

However the `tdwg_dwcterms.xsd` file lists the `substitutionGroup` for `taxonID` as being `dwc:anyIdentifier`, as can be seen here:

https://github.com/tdwg/dwc/blob/gh-pages/xsd/tdwg_dwcterms.xsd#L371

I can see in [`tdwg_dwc_class_terms.xsd`](https://github.com/tdwg/dwc/blob/gh-pages/xsd/tdwg_dwc_class_terms.xsd) that the `Taxon` class lists the possible `choice` elements as including `dwc:anyIdentifier` but there doesn't seem to be any way of knowing which of the terms in `tdwg_dwcterms.xsd` with the `dwc:anyIdentifier` attribute should go in which class.  

What am I missing here?

FYI, I am trying to build a simple Map<String, List> of `class -> list of terms`, as background.

**Comment by baskaufs** [comment]
The "ID" terms in Darwin Core have meanings that are somewhat dependent on their context.  They definitely refer to identifiers, but in some cases they act as primary keys and in other cases they act as foreign keys.  There is more information about this here: http://rs.tdwg.org/dwc/terms/guides/rdf/index.htm#2.6_Darwin_Core_ID_terms_and_RDF

**Comment by nickdos** [comment]
Thanks Steve, I gathered that. 

My question is basically, how can I generate the "class" attribute, as shown for each term on: http://rs.tdwg.org/dwc/terms/, by parsing the schema files (or any other way, programmatically). 

I.e., I want the "assumed" context for the above URL. 

So for [`TaxonID`](http://rs.tdwg.org/dwc/terms/#taxonID), I'd expect to get `http://rs.tdwg.org/dwc/terms/Taxon`

**Comment by baskaufs** [comment]
To find the class within which a term is organized, you can obtain that 
through its property 
<http://rs.tdwg.org/dwc/terms/attributes/organizedInClass>.  Now that 
the Standards Documentation Specification is done, we are working 
towards making machine-readable metadata available when a term is 
dereferenced.  At that point, you could get JSON-LD that would have all 
of the properties of any term, including dwc:taxonID.  That isn't 
happening yet, but hopefully it will happen soon. 

All of the DwC terms are loaded into the Vanderbilt Library SPARQL 
endpoint at http://rdf.library.vanderbilt.edu/sparql?view, where you can 
perform the query

SELECT DISTINCT ?class WHERE {
<http://rs.tdwg.org/dwc/terms/taxonID> 
<http://rs.tdwg.org/dwc/terms/attributes/organizedInClass> ?class.
}

Unfortunately, the endpoint currently only returns XML, but we are 
working on one that will return JSON as well.  You can CURL an HTTP GET 
containing the query above in URL-encoded form:

http://rdf.library.vanderbilt.edu/sparql?query=SELECT+DISTINCT+%3Fclass+WHERE+%7B%0D%0A%3Chttp%3A%2F%2Frs.tdwg.org%2Fdwc%2Fterms%2FtaxonID%3E+%3Chttp%3A%2F%2Frs.tdwg.org%2Fdwc%2Fterms%2Fattributes%2ForganizedInClass%3E+%3Fclass.%0D%0A%7D

which will result in:

<?xml version='1.0' encoding='UTF-8'?>
<sparql xmlns='http://www.w3.org/2005/sparql-results#'>
    <head>
        <variable name='class'/>
    </head>
    <results>
        <result>
            <binding name='class'>
                <uri>http://rs.tdwg.org/dwc/terms/Taxon</uri>
            </binding>
        </result>
    </results>
</sparql>

You can pull the value you want from the inner XML element.  If you 
substitute any other term for "taxonID", you can get the class that the 
other term is organized in.  We've been trying to keep this endpoint up 
and it's been running more or less continuously for a couple years now.  
So for the moment you could probably build an application to make calls 
to it as long as you don't hit it too fast and too hard.  Eventually we 
hope to replace it with a generic endpoint at 
https://lod.vanderbilt.edu/sparql, which would be a stable URI.  But we 
are still trying to make that happen.

Steve

-- 
Steven J. Baskauf, Ph.D., Senior Lecturer
Vanderbilt University Dept. of Biological Sciences

postal mail address:
PMB 351634
Nashville, TN  37235-1634,  U.S.A.

delivery address:
2125 Stevenson Center
1161 21st Ave., S.
Nashville, TN 37235

office: 2128 Stevenson Center
phone: (615) 343-4582,  fax: (615) 322-4942
If you fax, please phone or email so that I will know to look for it.
http://bioimages.vanderbilt.edu
http://vanderbilt.edu/trees

**Comment by nickdos** [comment]
Thanks for the detailed response @baskaufs - I'll take a look at that.

**Comment by tucotuco** [comment]
Answered. Closing.
