### ISSUE TITLE
etymology term

### ISSUE THREAD

**Issue by hughmacintosh** [tdwg/dwc#155]
I would like to propose a new term for including in DarwinCore: Etymology. This would allow for comments on the definition or origin of the scientific name (either the specific epithet or higher ranks). This might seem like a trivial addition, but it is standard when describing species to include a rationale for the taxon name; names can reflect an aspect of the organism's biology, locality or may be an honorific term. I believe it is important that this information is included with other commentary on a species' nomenclature, and leaving it out of DarwinCore is an oversight that should be corrected.

No existing DarwinCore term will suffice. At present there are no dedicated fields to comment on etymology, and including this information in general remarks will lead to inconsistent usage and muddies other comments on the usage of the name. The existing taxonRemarks term is best reserved for general comments on the taxon's name usage (rather than origins), such as noting previous misspellings or other miscellaneous comments. 

Taxonomic-focused databases such as the World Register of Marine Species (WoRMS) already include etymology as part of their comments on scientific names (for example see http://www.marinespecies.org/aphia.php?p=taxdetails&id=710133)

I propose that the 'etymology' term be used as following:

**Term Name**: etymology
**Identifier**: http://rs.tdwg.org/dwc/terms/etymology
**Namespace**: http://rs.tdwg.org/dwc/terms
**Label**: Etymology
**Definition**: The definition or origins of the ScientificName, with comments on the language used and author's intended meaning
**Comment**: Examples: "From the Greek, psammon- ("sand") and philos ("friend"), referring to the interstitial life habit of the adults (_Meioglossus psammophilus_)"; "named 'euiini' by authors after "the late Prof. Eui-In Paik who pioneered taxonomic studies on Korean polychaetes" (_Perinereis euiini_)"; "Spio has its origin in the Greek mythology, designating one of the Nereids, the 50 daughters of Nereus by Doris, goddesses of the sea, and patrons of sailors and fishermen. Spio (Speio, in Greek), was the nereid of the sea caves. (_Spio_)"; For discussion see http://terms.tdwg.org/wiki/dwc:etymology
**Type of Term**: http://www.w3.org/1999/02/22-rdf-syntax-ns#Property
**Refines**:
**Status**: Recommended
**Date Issued**: YYYY-MM-DD
**Date Modified**: YYYY-MM-DD
**Member Of:**
**Has Domain:**
**Has Range**:
**Decision:**	
**Version**: etymology-YYYY-MM-DD
**Replaces**:
**Is Replaced By**:
**Class**: http://rs.tdwg.org/dwc/terms/Taxon
**ABCD 2.06**: not in ABCD

**Comment by tucotuco** [comment]
@hughmacintosh 

Apologies for the lack of action on this proposal for so long. The Maintenance Group has finished with a long-awaited realignment with the standards specifications and are now ready to move forward on the long list of pending proposals.

This request involves the creation of a new term, thus, in accordance with the Vocabulary Maintenance Standard (VMS) Section 3 it requires a full review, a public commentary, ratification if warranted, and then implementation.

We are at the stage in the process where we have to demonstrate that the three main requirements for moving forward a change request are met. From the VMS Section 3.1:

Because the primary purpose of TDWG vocabularies is to facilitate data sharing, it is necessary to show that multiple parties will benefit from the change. As such, it is a minimum requirement that two independent entities indicate that they desire the change (the demand requirement). Additionally, it is required that there is a consensus within the community that the proposed change will accomplish the desired outcome (the efficacy requirement), and that making the change will not adversely affect the interoperability of existing implementations that depend on the stability of the vocabulary (the stability requirement).

Before the proposal goes to public review, the demand requirement has to be demonstrated. It is the burden of those proposing to make this case. It has not been made explicit so far. With this prerequisite satisfied, the proposal can move forward. The Darwin Core Maintenance Interest Group has its open annual review meeting on 2020-09-23T14:30+00:00, during which we will attempt to make progress on as many open issues as possible. The more mature a justification is, the further along we can move a proposal.

**Comment by nielsklazenga** [comment]
Is this not more a Plinian Core thing?

**Comment by tucotuco** [comment]
Closing for lack of demand.
