### ISSUE TITLE
New term - dwciri:measurementValue

### ISSUE THREAD

**Issue by pieterprovoost** [tdwg/dwc#175]
## New term

* Submitter: Pieter Provoost
* Proponents (at least two independent parties who need this term): @peterdesmet (TrIAS project), @dagendresen (GBIF Norway), @Daphnisd (EurOBIS), @pieterprovoost (OBIS)
* Justification: Multiple terms exist in the `dwciri:` namespace for the `MeasurementOrFact` class, but `measurementValue` is missing. While IRI references do not make sense for numeric measurement values, there are use cases for IRI values for generic facts and qualitative measurements such as sampling gear, sex, lifestage, etc.   

### Proposed definition of the new term:

* Term name (in lowerCamelCase): `dwciri:measurementValue`
* Class (e.g. Location, Taxon): http://rs.tdwg.org/dwc/iri/
* Identifier: http://rs.tdwg.org/dwc/iri/measurementValue
* Definition of the term: The value of the measurement, fact, characteristic, or assertion.
* Comment (examples, recommendations regarding content, etc.): Examples: [`http://vocab.nerc.ac.uk/collection/L22/current/TOOL0960/`](http://vocab.nerc.ac.uk/collection/L22/current/TOOL0960/)

**Comment by baskaufs** [comment]
It would probably be a good idea for the Darwin Core Maintenance Group to talk about this issue.  I'm not sure that the DwC RDF Guide explicitly says it, but I think there is an implicit understanding that a dwciri: analog of a dwc: term should exist any time that it makes sense to refer to the value of a Darwin Core property using a URI.  I can say that criterion was what we used when deciding whether to put terms in Table 3.7 [1] or Table 3.4 [2].  Assuming that kind of understanding, perhaps dwc:measurementValue should just be moved from Table 3.4 to Table 3.7 and have dwciri:measurementValue just pop into existence.

Section 3.4.1 of the Vocabulary Maintenance Specification [3] gives the vocabulary maintenance group some latitude to decide the extent to which it is necessary to go through the full change process to implement a particular change.  In this case, I suppose since dwciri:measurementValue is technically a new term, the full change process would be called for.  But if we were to adopt a new term in the dwc: namespace for which it would make sense to have a dwciri: analog, I would say that simultaneously creating the dwciri: analog would be a pro forma thing that would happen more or less automatically.  Actually, I suppose that whether or not there should be a dwciri: analog of a dwc: term or not is probably part of the conversation that should happen with every new term proposal.  But since this involves an analog of an existing term, it's too late for that. 

[1] http://rs.tdwg.org/dwc/terms/guides/rdf/index.htm#3.7_dwc:_namespace_terms_that_have_analogues_in_the_dwciri:_name
[2] http://rs.tdwg.org/dwc/terms/guides/rdf/index.htm#3.4_Terms_defined_by_Darwin_Core_that_are_expected_to_be_used_on
[3] https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md

**Comment by tucotuco** [comment]
I think this proposal is mature enough for public comment. It should be an easy one, as it really is a result of our oversight, and therefore almost an erratum, if it were not for coining a new term. We can present it as such. 

And yes, we have to be vigilant about keeping the dwciri: versions of term changes/additions in sync.

**Comment by tucotuco** [comment]
Done.
