### ISSUE TITLE
Deprecate individualCount

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#185]
**Proposed change**: It is proposed to deprecate the term individualCount (http://rs.tdwg.org/dwc/terms/index.htm#individualCount). 
**Justification for change**: 
The content for the term individualCount can be captured without loss by putting the value from individualCount in organismQuantity while populating organismQuantityType with the value 'individuals'.
**Comments**: There are two precedents for deprecating terms that have alternative representations. The term occurrenceDetails was deprecated in favor of dc:references (see Decision-2011-10-16_7 on http://rs.tdwg.org/dwc/terms/history/decisions/index.htm), and the term dc:rights in Darwin Core was deprecated in favor of dc:license (see Decision-2014-11-06_17 on http://rs.tdwg.org/dwc/terms/history/decisions/index.htm).

**Comment by eclites** [comment]
We discussed this proposed change at the EPICC TCN meeting and strongly recommend that this field not be deprecated because it is a standard field used across paleontological specimens.

**Comment by tucotuco** [comment]
@eclites Given that there is a standard equivalent field, what would be lost by using organismQuantity in place of individualCount? In terms of data publication, it is trivial to map whatever is going into individualCount now into organismQuantity instead, and to add "individuals" to organismQuantityType. Since there would be no loss of information of capability, I am curious why the strong recommendation not to deprecate this now-redundant field.

**Comment by qgroom** [comment]
I would prefer there to be an established controlled vocabulary for `organismQuantityType` before organismQuantity were deprecated. Otherwise people might use "number", "count" or some other word meaning the same thing.

**Comment by eclites** [comment]
We prefer individualCount because it is more ambiguous than organismQuantity. We need the ambiguity because "individual specimen" is not necessarily equivalent to "individual organism" when it comes to fossil parts. Also, there are different methods for estimating organisms from parts dependent on the organism under consideration. For the paleo field, we don't find the meaning to be redundant.

**Comment by tucotuco** [comment]
@qgroom I totally understand the desire to have a controlled vocabulary in place, and it seems good as a prerequisite to a deprecation. 

@eclites The value of organismQuantityType could be exactly what you need it to be, rather than my ill-chosen value of "individuals". By using a controlled vocabulary value that meant exactly what need, you would gain over what individualCount provides for you, because individualCount is explicitly about the number of individuals (not ambiguous). To use individualCount for a specimen count is actually a mis-use, unless they happen to be the same number.  But maybe I completely misunderstand. Can you give an example of something you represent routinely with individualCount that could not be represented with organismQuantity and organismQuantityType?

**Comment by eclites** [comment]
@tucotuco We generally count numbers of specimens rather than number of organisms. There are standard formulae that are used to estimate the number of individual organisms from the number of individual specimens for disarticulated bivalve shells, and crinoid ossicles. This is a standard approach in paleoecology as we rarely expect our piles of shells, bones, conodont elements, etc. to be numerically equal to the number of individuals from which those specimen pieces originated. Our group isn't all in agreement--@hollyel thinks adopting the new proposed terms is a good idea. It would be a non-trivial thing to split counts of specimens from counts of organisms and I doubt several of our institutions at least would be able to make the change.

**Comment by tucotuco** [comment]
@eclites I think I am still missing something. Couldn't collections, in place of using dwc:individualCount to signify a number of specimens, instead put the same number in dwc:organismQuantity with "specimens" or similar in dwc:organismQuantityType and thereby tell everyone exactly what is being counted? Maybe there is a misunderstanding that dwc:organismQuantity has to be a count of individuals - it doesn't.

**Comment by eclites** [comment]
@tucotuco I guess part of it depends on what the standard vocabulary for dwc:organismQuantityType ends up being. I know it would not be small process to try to sort out which ones were individuals vs. specimens in our current data and that might mean that people don't serve anything more meaningful than the current situation.

**Comment by tucotuco** [comment]
Is that because it could be mixed in a given single data set?  Wouldn't they always be "specimens" and sometimes also "individuals"?

**Comment by seltmann** [comment]
I heard about this proposal at the iDigBio summit meeting and I thought it important to add another perspective as I and my colleagues use individualCount (monitoring data, entomology) a lot in our work. We use individualCount to indicate number of specimens in a lot (in alcohol). We understand it is a group of specimens because of the basisOfRecord. Doing this is an important part of our process as lots can be stored for several years before sorting out to individual specimens.

We also use individualCount commonly in recording observation data.

I understand the idea of making the darwin core parsimonious, but what is the harm in leaving a useful and commonly used term? I only see it as creating unnecessary work for people trying to manage databases.

Thanks,
Katja

**Comment by qgroom** [comment]
@seltmann Interesting comment! I've also come across situations like this where the context of the record described elsewhere in the DwC record modifies the meaning of a term, at least in the user's mind if not officially.
I can only think this can be solved by extending the documentation of each term, however, because the term descriptions are normative one cannot just change them without discussion. I feel we need a way in which we can discuss term definitions and implement changes, without too much additional work.

Would it satisfy @tucotuco if the term definition of `individualCount` restricted its use to specimens? This might be marginally less disruptive than deprecating it.

**Comment by tucotuco** [comment]
Hi folks. A bit of a delay there, but not from lack of interest. @qgroom  I don't have any need to be satisfied. I was just attempted to do a little cleanup in a situation where it seemed obvious and trivial. 

I've looked at all the arguments, and I understand how the term is being used, but I have seen nothing to suggest that it isn't completely redundant. dwc:individualCount is doing nothing that the other two terms can't do. It's just that dwc:individualCount is entrenched and there would be a term-mapping impact if it were deprecated. That seems a small price to pay at the community level to have more clarity and consistency about where this information should reside. That having been said, I can't take action where there isn't consensus. I was just seeking it here.

**Comment by tucotuco** [comment]
From issue #223 discussion:

@qgroom "I'm sympathetic to the difficulties of getting rid of fields such as dwc:individualCount. However, in that case people are using it to fulfill a need not currently accommodated. That is, documenting the number of individuals that makes up a specimen, rather than the count of the number of individuals in a population/observation. In the case of dwc:startDayOfYear, dwc:endDayOfYear and dwc:year they can all be calculated from dwc:eventDate or used to populate dwc:eventDate if it is empty. We don't have a separate year for all the other dates in DwC, only the event date.

Even if something is deprecated it doesn't stop people using it, it just doesn't encourage people to use it."

@tucotuco "The number of individuals that make up a specimen can be accommodated with a dwc:organismQuantity and dwc:organismQuanityType="individuals in specimen". to me dwc:individualCount is utterly redundant aside from the fact that it was there first."

@anderspi "dwc:individualCount is far from redundant given that you would like to express more than one dimension of organism abundance in a simple dwc format. e.g. dwc:individualCount="1", dwc:organismQuantity="129", organismQuantityType="biomassG". For applications of the data, it is often extremely useful or even necessary to know how many individuals that the measure of biomass is based upon."

**Comment by tucotuco** [comment]
@andersfi This is the first demonstration I have seen that dwc:individualCount can be used to convey additional information - when organismQuantity is used for something else. Your case could be captured in an alternative way without the need for individualCount, also without loss of information.

organismQuanity = 1
organismQuantityType = individuals
dynamicProperties = { biomassInGrams:129 }

I won't say that it is better, only that the same information is shared.

**Comment by tucotuco** [comment]
Change rejected following public commentary.
