### ISSUE TITLE
add term relationshipAccordingToID to Resource Relationship extension

### ISSUE THREAD

**Issue by jhpoelen** [tdwg/dwc#187]
Suggest to add relationshipAccordingToID to Resource Relation extension to help link human readable text (e.g., some citation) to a machine readable identifier (e.g., some doi) . 

For discussion see trias-project/uredinales-belgium-checklist#8 (comment) .

**Comment by peterdesmet** [comment]
This proposal needs more **evidence for demand** (see the [Vocabulary Maintenance Specification - Section 3.1](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#31-justifications-for-change)). Anybody who is interested in the adoption/change of this term, should comment with their use case below. If demand is not demonstrated by the next annual review of open proposals (late 2020), this proposal will be dismissed.

@jhpoelen note that #186 will be submitted for public review.

**Comment by jhpoelen** [comment]
@peterdesmet excellent - thanks for the update. I hope that #186 (once approved) will be sufficient to get more folks to use Resource Relationship extension for species interactions.

**Comment by tucotuco** [comment]
Hi @jhpoelen,

This request involves the creation of a new term, thus, in accordance with the [Vocabulary Maintenance Standard (VMS)](https://www.tdwg.org/standards/vms/) Section 3 it requires a full review, a public commentary, ratification if warranted, and then implementation. 

We are at the stage in the process where we have to demonstrate that the three main requirements for moving forward a change request are met. From the VMS Section 3.1:

> Because the primary purpose of TDWG vocabularies is to facilitate data sharing, it is necessary to show that multiple parties will benefit from the change. As such, it is a minimum requirement that two independent entities indicate that they desire the change (the **demand** requirement). Additionally, it is required that there is a consensus within the community that the proposed change will accomplish the desired outcome (the **efficacy** requirement), and that making the change will not adversely affect the interoperability of existing implementations that depend on the stability of the vocabulary (the **stability** requirement).

Before the proposal goes to public review, the demand requirement has to be demonstrated. It is the burden of those proposing to make this case. It has not been made explicit so far. In order to facilitate assessment, it is essential that the complete proposal be made explicit as well. Have a look at the  the [Guidelines for contributing](https://github.com/tdwg/dwc/blob/master/.github/CONTRIBUTING.md) and the following issues as examples of how to do that:

https://github.com/tdwg/dwc/issues/237
https://github.com/tdwg/dwc/issues/246

With the two prerequisites described above satisfied, the proposal can move forward. The Darwin Core Maintenance Interest Group has its open [annual review meeting](https://www.tdwg.org/conferences/2020/working-sessions/#itg02:%20darwin%20core%20maintenance%20group) on [2020-09-23T14:30+00:00](https://www.tdwg.org/conferences/2020/working-sessions-schedule/), during which we will attempt to make progress on as many open issues as possible. The more mature a justification is, the further along we can move a proposal.

**Comment by tucotuco** [comment]
This proposal is in danger of not being included in the pending public review, scheduled to be announced 2021-05-01. See https://github.com/tdwg/dwc/issues/187#issuecomment-687281136 for what still needs to be done to be included.

**Comment by jhpoelen** [comment]
@tucotuco thanks for letting me know about the upcoming review. I am okay to put #187 in some future public review and focus on making sure that #186 gets through review first. Please confirm that the review "paperwork" #186 is complete. Small steps. . .

**Comment by tucotuco** [comment]
I assume you are wondering about the status of Issue #283. That proposal is ready for public review. Issue #186 has been closed.

**Comment by jhpoelen** [comment]
@tucotuco Thanks for confirming review status of proposal https://github.com/tdwg/dwc/issues/283  and for pointing to the more appropriate issue reference.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
