### ISSUE TITLE
Create Extensions Task Group 

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#188]
The process of making Darwin Core extensions is ill-defined and ill-documented. Create a task group to better define and document the process, including the missing piece of making extensions into standards. Some standards, such as ResourceRelationship, which are based on Darwin Core only, could be put through this process as a deliverable. Should also define how extensions can come out of other interest groups and what role the Darwin Core Maintenance Group should play in that.

Another deliverable of this task group might be to clean up the two MeasurementOrFact Extensions. Yet another might be to document how extensions can be used to overcome/sidestep the star schema constraint.

**Comment by baskaufs** [comment]
Because of the confusion about how complex additions to a vocabulary should be handled (as was the case with creating the DwC RDF guide), the Vocabulary Maintenance Specification describes a process (in [Section 4](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#4-vocabulary-enhancements)) for creating "vocabulary enhancements".  That's a term that is intentionally vague because it is intended to apply to all kinds of coordinated sets of changes to a vocabulary that go beyond adding or changing a single term.  The relevant points are:

1. A "working group" (either ad hoc or chartered as a Task Group) develops the set of changes and submits it as a single proposal.  
2. The proposal must include a "feature report".  Again, this is vague, but is an attempt to follow the best practices of our peer organizations.  It may include collecting use cases or competency questions.  The point is that the working group must show specifically what the community wants the enhancement to do.
3. The proposal must include an "implementation experience report".  This is another vague term, but this report has to show that the proposal has actually been demonstrated  by two independent implementations to satisfy the use cases identified in the feature report.  If that isn't possible, then the "feature" must be dropped.

The point of this all is to avoid the years of endless chatter on tdwg-content that would be required to hash out coordinated additions to a vocabulary in the absence of a clear, coordinated process.  The gory details should be worked out BEFORE the proposal is made, rather than after.

So far, there haven't been any examples of making this process work, although the Audubon Core Maintenance Group is close to chartering a 3D task group that will go through this process to create a set of new terms needed to handle 3D images in AC.  

The role of the chartering Interest Group (in this case the DwC MG) is spelled out in section for of the VMG, so I won't repeat it here - just go to the spec and read it.

**Comment by tucotuco** [comment]
The Vocabulary Maintenance Specification describes the process this issue was meant to address. Closing.
