### ISSUE TITLE
Mimetype for DwC-A

### ISSUE THREAD

**Issue by jhpoelen** [tdwg/dwc#195]
Hi! 

Is there an official mimetype for Darwin Core archives? 

Something like "application/dwca" ?

Would be great to have a way to describe the format similar to a https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types way.

Curious to hear your thoughts...

**Comment by ansell** [comment]
I like the (not always used) convention of adding ``+zip`` to the end of archive file types that are zipped, but that isn't strictly necessary.  ``application/dwca`` and ``application/dwca+zip`` both work for me

**Comment by mdoering** [comment]
I am not aware of anyone using a dwca specific mime type. As the archive can be bundled in various ways this would need to be reflected. DwC-A alone does not specify how to bundle or compress it (I think we miss that part and it should better also be part of the specs). We see people using zip and gzip in GBIF, I am not aware of any other.

**Comment by cgendreau** [comment]
A dwca MimeType is used in the OAI-PMH response:
http://api.gbif.org/v1/oai-pmh/registry?verb=ListRecords&metadataPrefix=oai_dc&set=Country:TG

`"<dc:format>application/dwca+zip</dc:format>"`

If I remember correctly, `dc:format` is mandatory and we wanted to be more precise than simply zip. So we decided to exposed that mime type. I'm not saying it's the right thing to do considering, like @mdoering mentioned, there is no explicit definition on how to bundle a DwC-A. Is it good enough? I don't know but it might be for most of the use cases.

**Comment by jhpoelen** [comment]
interesting, perhaps we can do multiple types to reflect packaging:

```application/dwca``` (packaging unspecified, so consumers will have to guess)
```application/dwca+zip``` (zip)
```application/dwca+tgz``` (tar balls)

sounds a bit overly complex.  Thoughts?

**Comment by mdoering** [comment]
Feels weird to me to mix up the compression with the included data. Is that common practice for jpegs or other files? If we want a mime type I feel the best would be to use application/dwca and mandate that its zipped in the specs. That would ease a consumers life too

**Comment by jhpoelen** [comment]
@ansell @mdoering @cgendreau  sounds like we have consensus on using ```application/dcwa``` as "the" mimetype for DwC-A with an option of using ```+zip``` suffix . I think this would reflect common usage.

Please confirm and we can move forward to document and register the mimetype.

**Comment by ansell** [comment]
The use of ``+zip`` as a suffix isn't universal for zipped formats. For example the ``.docx``/``.xlsx``/etc. Microsoft Office OOXML formats are all PKZIP compressed, but they don't contain ``+zip`` in their content types: https://docs.microsoft.com/en-us/previous-versions/office/office-2007-resource-kit/ee309278(v=office.12). The same applies to the Oasis OpenDocument ``.odt``/``.ods``/etc. formats https://www.openoffice.org/framework/documentation/mimetypes/mimetypes.html Those that do are relatively rare in comparison.

However, if there is a precedent with the GBIF OAI-PMH metadata previously using ``application/dwca+zip`` I would tend to recommend that rather than ``application/dwca`` if the vast majority of archives are PKZIP compreassed. Anecdotally, all of the ones I have dealt with and created at ALA use PKZIP.

Whether ``application/dwca`` or ``application/dwca+zip`` is chosen, mandating one compression format in the specifications for future implementors would be useful (similar to OOXML/OpenDocument). Lenient software could use magic numbers or file extensions to detect legacy archives created using GZIP (``.gz``) rather than PKZIP (``.zip``) in either case to load them correctly.

**Comment by mdoering** [comment]
I agree with @ansell and we should pick just one mime type. Some discussion about adding +zip or +xml to a mime type suffix thats interesting: https://www.ietf.org/mail-archive/web/ietf-types/current/msg00998.html
Sounds to me dwca+zip makes most sense in that light.

But isn't it really difficult to register a new mime type with IANA? Maybe the vendor specific or unregistered tree is a more realistic option?
https://en.wikipedia.org/wiki/Media_type#Registration_trees

**Comment by cgendreau** [comment]
I agree that, based on that email thread, I think the answer to the following question is yes for DwC-A:

> Is being able to perform generic processing of
> formats packaged using ZIP useful even when you cannot process the specific
> type? If the answer is yes, then +zip makes sense, if not, then it doesn't.

**Comment by tucotuco** [comment]
I am trying to clean up aging issues. Is there someone who can take this one to completion?

**Comment by jhpoelen** [comment]
@tucotuco thanks for keeping an eye out for stale issue.

What I took from this discussion is that folks already use dwca mimetypes like ```application/dwca``` and ```application/dwca+zip```, but formally registering the type with IANA is a lot of work. 

Suggest to close issue.

**Comment by tucotuco** [comment]
@jhpoelen Agree. Closing.
