### ISSUE TITLE
Update links on guides

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#198]
The guides contain some links in their metadata, which will need to be updated. E.g.

> Part of TDWG Standard
> http://www.tdwg.org/standards/450/
> This version
> http://rs.tdwg.org/dwc/terms/simple/2014-11-08
> Latest Version
> http://rs.tdwg.org/dwc/terms/simple/
> Previous version
> http://rs.tdwg.org/dwc/terms/simple/2013-10-22
> Bibliographic citation
> Darwin Core Task Group. 2009. Simple Darwin Core. Biodiversity Information Standards (TDWG). http://rs.tdwg.org/dwc/terms/simple/

**Comment by baskaufs** [comment]
Do you  mean updated with respect to the version dates?  Because otherwise, the URIs should remain the same.  I've almost got the redirects ready to go for rs.tdwg.org

**Comment by peterdesmet** [comment]
I meant the domain, but you're right: those will be redirected and can thus remain the same. Leaving issue open for testing.

**Comment by baskaufs** [comment]
OK, I'm getting close.  I've implemented all of the redirects in [the server script](https://github.com/tdwg/rs.tdwg.org/blob/master/html/restxq.xqm), although document versions arent currently supported, since I don't know where some of the older ones are.  I'm currently testing at http://vuswwg-private.jelastic.servint.net/gom/, which substitutes for http://rs.tdwg.org/ in the URLs.  For example, use http://vuswwg-private.jelastic.servint.net/gom/dwc/terms/guides/text/ to test what would happen with http://rs.tdwg.org//terms/guides/text/.  If I finish the tests tomorrow, I'll get Matt to copy the server script to his test server for final testing.

**Comment by peterdesmet** [comment]
These links are are functional. All versions link to the latest versions, but I think that is intentional.
