### ISSUE TITLE
Redirect anchor remains uppercase while actual anchor is lowercase

### ISSUE THREAD

**Issue by katrinleinweber** [tdwg/dwc#216]
Dear @peterdesmet,

I think I noticed a problem related to #203: http://rs.tdwg.org/dwc/terms/MaterialSample redirects to https://dwc.tdwg.org/terms/#MaterialSample, but the HTML anchor is actually spelled in all lowercase: https://dwc.tdwg.org/terms/#materialsample.

Same problem with all class names. Maybe because they start with an uppercase letter and a lower-case conversion function is missing for generating the redirect, but is present when generating the HTML anchor?

**Comment by tucotuco** [comment]
This is no longer the behavior. Now http://rs.tdwg.org/dwc/terms/MaterialSample redirects to https://dwc.tdwg.org/list/#dwc_MaterialSample.

Is this the desired behavior?

**Comment by peterdesmet** [comment]
Tagging @baskaufs on this one.

**Comment by baskaufs** [comment]
That is the desired behavior. The term dereferencing now redirects to the new "list of terms" document instead of the Quick Reference Guide for two reasons:

1. The list of terms is a document that is included in the DwC standard, and which indicates which parts of the term metadata are normative and which are not. The QRG doesn't do that. 
2. In the past, there were complaints that terms in the `dwc:` namespace that are no longer recommended did not dereference to anything. The "list of terms" document contains every term ever issued in the `dwc:` namespace (with an indication of whether it was no longer recommended for use, if appropriate). The QRG does not and that's why trying to dereference non-recommended terms sent people to never-never land. 

I believe that this is the correct approach, given that people who try to dereference a full IRI are probably trying to find authoritative information about a term and the list of terms would be that source. 

BTW, the redirect is controlled [here](https://github.com/tdwg/rs.tdwg.org/blob/master/html/redirects.csv). It can be changed by just pushing a change to that document.

**Comment by tucotuco** [comment]
Excellent. Closing.
