### ISSUE TITLE
Standard format for agent names

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#218]
Is the format for names provided in the examples for dwc:recordedBy and dwc:identifiedBy, e.g. Theodore Pappenfuss | Robert Macey or Oliver P. Pearson | Anita K. Pearson a standard? Should agent names always appear as [firstname] [initials with periods] [lastname]. The definitions don't appear to specify name formats.

**Comment by tucotuco** [comment]
No, the examples should not be assumed to represent any standards. I am not sure if there can be a single standard format for names in all of biodiversity. All we need are two conflicting examples to determine this for sure. The counter, that there is a single standard way to do it, might be much harder to prove.

**Comment by qgroom** [comment]
As it happens I have just returned from a workshop on person identifies for
collections (https://osf.io/qwegk/). What you propose is fine. As John
says, there isn't a standard for people name strings and it wouldn't help
much if there was one.
More importantly is to connect your people to a unique identifier. VIAF,
ISNI. ORCID ID and/or Wikidata. This can be included in Darwin Core as
dwciri:recordedBy . However, this only works well for individuals and the
problems of collector teams has yet to be resolved satisfactorily.
Regards
Quentin

**Comment by Archilegt** [comment]
Hi,
I have a question. It is my understanding that dwc:recordedBy and dwc:identifiedBy are fields for verbatim data entry but I can't remember where I read or saw that information. Could someone please clarify this and provide the source? Thanks in advance!

**Comment by baskaufs** [comment]
I don't think that they have ever specifically been designated as for verbatim data. Rather, they may be used with some string. It might be reasonable to put a verbatim string as the value if it were accompanied by a well-known URI value (ORCID, VIAF, etc.) for dwciri:recordedBy (or dwciri:identifiedBy). However, if dwc:recordedBy (or dwc:identifiedBy) were the only value provided, it would probably be desirable to provide a name string that is as unambiguous as possible. For example, if the verbatim value was "A. Pearson", it would probably be better to provide "Anita K. Pearson" instead, since it is less ambiguous.  

Just my opinion, though.

**Comment by Archilegt** [comment]
Hi @baskaufs ,
I agree with you but it is often the case that the recorders want to fill the field verbatim and it is also often the case where a name cannot be properly deciphered or disambiguated. My question is not really about best practices but about the specifications for those fields. I know that I read that they were meant to be verbatim somewhere, I just can't remember where.
I think that the option of accompanying names by a well-known URI value is fairly recent, starting in April or so with the addition of dwc:recordedByID and dwc:identifiedByID. My memory on this "verbatim" question is previous to that time.

**Comment by baskaufs** [comment]
OK, I'm getting really confused here. I believe that I'm familiar with all of the normative Darwin Core documents and I've never seen any reference to using `dwc:recordedBy` or `dwc:identifiedBy` specifically with verbatim values. Also, I'm a member of the Darwin Core Maintenance Group and I'm unaware that there was any action ever taken to adopt `dwc:recordedByID` and `dwc:identifiedByID` as terms. There may have been discussion about them somewhere, but I can say pretty confidently that those terms don't actually exist. 

The ability to use `dwciri:` namespace terms with IRIs started with the adoption of the [Darwin Core RDF Guide](https://dwc.tdwg.org/rdf/) in 2015. So that's not a particularly recent development.  

You should be able to see the normative definitions of terms in the `dwc:` namespace by going here: <http://rs.tdwg.org/dwc/terms/> and all of the `dwciri:` namespace terms here: <http://rs.tdwg.org/dwc/iri/>.  In principle, these two documents should agree with the so-called "normative" Darwin Core document, which is here: <https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv> but is pretty much unreadable. I think the same information is present in both documents, but I haven't verified that.

**Comment by pzermoglio** [comment]
@baskaufs I believe @Archilegt may be referring to the new capabilities in the GBIF portal to search occurrences by recordedByID and identifiedByID, which was indeed announced late March - early April this year.

**Comment by Archilegt** [comment]
@pzermoglio yes, thanks. I forgot to say that those two new terms come from the [GBIF DwC extension for Occurrence](http://rs.gbif.org/core/dwc_occurrence_2020-04-15.xml). Sorry for the confusion with a different namespace.
Also, most likely I did not see the "verbatim use" of the fields on any DwC official document and maybe that is why it is so difficult to find now.
Okay, it may be that we are in a gray area here. My thinking/doubt/question is: There are primary DwC terms for capturing recorders' and identifiers' data. I believe that those primary terms are dwc:recordedBy and dwc:identifiedBy. Right? Now, from my nearly 15 years databasing museum collections, I would always try to capture verbatim label data into a primary data field/term/column. I consider useful to have not just one verbatim field with the full label text string but also columns with verbatim fragments of that text. And indeed DwC have several fields including "verbatim" in the name, e. g.: verbatimEventDate, verbatimLocality, verbatimElevation, verbatimCoordinates, etc, etc. Why additional terms don't exist for recorders and identifiers, I don't know. But looking at the big picture, if they don't exist in the form "verbatimRecordedBy" and "verbatimIdentifiedBy", any implementation of the terms should allow verbatim data entry, because otherwise there is no way to sort the verbatim values into existing fields.
I am bringing this problem forward because the Scratchpads virtual research environment at the moment has a rigid implementation of those two terms, which is making verbatim data entry really difficult. The recorders and identifiers are supposed to be "users" within the "People" module. That implies filling mandatory fields like name, e-mail, etc. On the other hand, the "Biblio" module does allow verbatim entry of Authors' names.
To wrap up: Would it be possible to update the documentation to make clear something like "Verbatim data entry is not mandatory but shall be allowed"? In the absence of additional terms, that is the most flexible recommendation that I can think of, allowing both verbatim and interpreted data entry.
Thoughts?

**Comment by baskaufs** [comment]
Thanks for the clarification, @pzermoglio and @Archilegt. That makes more sense to me now. I think the question is whether the clarification you are asking for is something that the Maintenance group can just add as a non-normative usage comment or whether it needs to be added to the normative definition (which would invoke an official term change process). We have typically put things like suggestions and examples in the usage comments, but if we are actually saying something like "... not mandatory but shall be allowed", then that is more prescriptive. It might make sense to propose the two new terms @Archilegt  suggested (verbatimRecordedBy and verbatimIdentifiedBy) and gauge the community response. That would allow for the use @Archilegt wants while maintaining dwc:recordedBy and dwc:identifiedBy to continue to be used with processed name data as the probably are most commonly used now.

**Comment by qgroom** [comment]
We recently published a paper to try and resolve some inconsistencies with transcribed data [](https://doi.org/10.1093/database/baz129).

For partially illegible names we recommend the Chicago Manual of Style (2017) formatting. This is already widely used by many transcribers anyway.

We also discuss verbatim transcription in general. Transcription is an interpretive process so in reality verbatim transcription is somewhat of an oxymoron. In our collection management system we diligently record the verbatim and interpreted collector name, but to be perfectly honest I'm not sure we've actually used the verbatim version and as more of our collection is imaged its value declines.

Chicago Manual of Style (2017) The Chicago Manual of Style, 17th edn. University of Chicago Press, Chicago.

**Comment by Archilegt** [comment]
Hi @qgroom ,
Thanks for the reference! I also searched for your paper and I think it should be [this one](https://doi.org/10.1093/database/baz129). I will try to read it this weekend. 
I work with wet collections, for which label imaging is a time-consumig process. That is why transcription and specially verbatim transcription is still very relevant to me.

Hi @baskaufs ,
I would like to go with your suggestion of proposing **verbatimRecordedBy** and **verbatimIdentifiedBy**. In that scenario, recordedBy and identifiedBy would most likely be used for the interpreted version of names. However, there will still be instances in which no interpretation is possible, and then the same value entered in verbatimRecordedBy and verbatimIdentifiedBy will be used to populate recordedBy and identifiedBy. I can also imagine someone proposing two data quality improvement steps in which "If 1) verbatimRecordedBy/verbatimIdentifiedBy is filled and 2) RecordedBy/IdentifiedBy is empty then fill 2) with 1)". Considering that, I would recommend not to rigidly define recordedBy and identifiedBy as "interpreted data fields with standardized values" but as flexible fields that could accommodate all sorts of values. And I would add a "flexibility" note to those fields in a way that makes it clear to developers. 

I am just a front-end user of Arctos but I have seen the MCZBase implementation of Arctos and they have a way of linking different spellings to one authority. Maybe someone here using Arctos could let us know which fields are used for storing spellings and authorities and how are they mapped to DwC fields upon download.

**Comment by pzermoglio** [comment]
This may be of interest to this topic:
https://github.com/tdwg/attribution/issues
The Attribution Interest Group is creating an extension, "AgentActions", that would contain a verbatimName term, and others, that could help accommodate some of the info targeted here.

**Comment by baskaufs** [comment]
Well, depending on the speed at which the Attribution IG makes progress, just using the term they are proposing may be the most straightforward way to go.

**Comment by qgroom** [comment]
The plan for the Attribution IG is to move rapidly and it would be good to have input from users such as @Archilegt
