### ISSUE TITLE
Clarification: stateProvince/county/municipality when georeference radius covers more than one

### ISSUE THREAD

**Issue by ianengelbrecht** [tdwg/dwc#221]
Using a point-radius (or a dwc:footprintWKT) for a georeference, and that radius encompasses several administrative divisions, what should go into these fields? The division that the points falls into, or a list of the divisions that the radius covers? 

To illustrate, the Matroosberg mountains in South Africa fall into two districts, the Worcester Distr. and the Ceres Distr. Some specimens are recorded from the 'Matroosberg', with no extra information. 

Should the answer to this be included in the documentation for these DwC properties?

**Comment by qgroom** [comment]
I think they should be left blank. The answer is not available.

Yes, it would be useful have this better documented, but this is a general problem and no solution seems to have been found yet.

**Comment by tucotuco** [comment]
Hi Ian,

This question is interesting as it approaches the georeference from a perspective opposite to the normal one for retrospective georeferencing. Usually, one has a textual location as raw material from which the georeference is derived. That is usually something akin to Darwin Core's verbatimLocality, where all of the details could be written out. The principles of best practice suggest that the spatial representation should contain all of the possible interpretations of where that textual location can be. That interpretation often intersects multiple entities at the same administrative level (e.g., dwc:stateProvince). But the Darwin Core higher geography terms are meant to be singular, so that they could, in principle, but validated from a geographic authority. We capture that principle in the standardization of geography using the VertNet Geographic Lookup file (see https://github.com/VertNet/DwCVocabs/blob/master/vocabs/Geography.csv and the principles behind it at https://github.com/VertNet/DwCVocabs). Summarizing, to answer you question, I agree with @qgroom, the administrative levels that would have multiple values should be left blank, and the parent administrative level that contains all of the location should be provided. I have cross-referenced this issue in The Darwin Core Questions & Answers repository (see https://github.com/tdwg/dwc-qa/issues/141), where issues lead to documentation improvement.

**Comment by ianengelbrecht** [comment]
Thank you for the responses John and Quentin. Blank it will be. Just another example, which may be useful for documentation, would be a verbatimLocality of '5km from Rust de Winter, Transvaal'. Our South African provinces were changed in 2004, with the Transvaal split into four. A radius of 5km around the small town of Rust de Winter includes three, namely Gauteng, Limpopo and Mpumalanga. To further complicate matters, our provincial boundaries are still somewhat fluid, with the last set of changes in 2016, which puts stateProvince values near but within provincial boundaries in peril too.

**Comment by tucotuco** [comment]
I am going to keep this one open, following our process to not close the issue until the answers have been incorporated in documentation.

**Comment by tucotuco** [comment]
The usage comments for country incorporate the recommendations covered here. The remaining administrative geography terms (continent, countrycode, stateProvince, county, municipality) should do the same.

**Comment by tucotuco** [comment]
Closing as having been answered.
