### ISSUE TITLE
startDayOfYear and endDayOfYear, year, month, day

### ISSUE THREAD

**Issue by qgroom** [tdwg/dwc#223]
Why has Darwin Core got `startDayOfYear` and `endDayOfYear` terms when these can be derived from `eventDate`? It is difficult to know how to determine these terms when `eventDate` is a range and spans more than a year.

Also, I can understand that Darwin Core needs `month` and `day`, because sometimes these data are available when the year is not. Apparently, ISO8601 does not support an unknown year ([https://en.wikipedia.org/wiki/ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)).
However, this means the `dwc:year` is redundant, it can always be derived from `dwc:eventDate`.

What is the argument for keeping `dwc:startDayOfYear`,  `dwc:endDayOfYear` and `dwc:year`?

**Comment by tucotuco** [comment]
These two terms derive from a term that was in the original release of Darwin Core as far back as 1999. At the point the term was (incorrectly) named JulianDay. One of the principles behind the first release of Darwin Core as a standard in 2009 was to not lose any concepts that were already in use. Since the original year, month, day were deemed insufficient to express events, the concept of JulianDay turned into the two terms we have today. That's the history justification. The utility justification is that these can be very interesting to use as search terms when it comes to questions such as phenology. Just because they can be derived from eventDate doesn't mean they aren't useful concepts to define, and Darwin Core is made for defining concepts.

As for populating them in the case you present, it is no different from any other case. use the day of year for the earliest date (not smallest day of year, necessarily) for the startDayOfYear and the day of year for the most recent date (not largest day of year, necessarily) for the endDayOfYear. If the eventDate spans a single day, use the same value for both startDayOfYear and endDayOfYear.

Similar arguments hold for dwc:year, which has also been with us (DwC) since the beginning.

Recent attempts to suggest the removal of the utterly redundant dwc:individualCount (https://github.com/tdwg/dwc/issues/185) and the inability to reach a consensus on the removal of ANY Darwin Core term in the Kill Your Darwin Core Darlings Initiative (https://docs.google.com/forms/d/e/1FAIpQLScgQn291GufuaJB6bsbNhqOhWBpFXaqDtXMjmq2WqEQBe1_mA/viewform) suggest that removal of terms is an immense challenge once they come into practice. This is particularly true of those that are entrenched. 

Of 1,213,409,995 Occurrence records in GBIF as of 2019-04-15, 869,895,712 (71.6%) include dwc:year in the original data. The percentage for dwc:startDayOfYear and dwc:endDayOfYear are 9.1% and 8.2% respectively.

**Comment by qgroom** [comment]
Certainly, year is a useful term to search on, though most, if not all, databases will do this on-the-fly from a date. I have certainly populated `dwc:year` in some of my datasets, just because I felt I was being more complete. However, it is redundant and potentially a source of error and confusion.  Obviously, year is not much use for search if `dwc:eventDate` is consistently populated.

I'm sympathetic to the difficulties of getting rid of fields such as `dwc:individualCount`. However, in that case people are using it to fulfill a need not currently accommodated. That is, documenting the number of individuals that makes up a specimen, rather than the count of the number of individuals in a population/observation. In the case of `dwc:startDayOfYear`, `dwc:endDayOfYear` and `dwc:year` they can all be calculated from `dwc:eventDate` or used to populate `dwc:eventDate` if it is empty. We don't have a separate year for all the other dates in DwC, only the event date.

Even if something is deprecated it doesn't stop people using it, it just doesn't encourage people to use it.

**Comment by tucotuco** [comment]
It is true that dwc:year, dwc:startDayOfYear and dwc:endDayOfYear may be derivable from a dwc:eventDate, but it is not necessarily trivial to do so in everyone's everyday working environment. I think it is a service to added provide these.

The number of individuals that make up a specimen can be accommodated with a dwc:organismQuantity and dwc:organismQuanityType="individuals in specimen".  to me dwc:individualCount is utterly redundant aside from the fact that it was there first.

**Comment by andersfi** [comment]
dwc:individualCount is far from redundant given that you would like to express more than one dimension of organism abundance in a simple dwc format. e.g. dwc:individualCount="1", dwc:organismQuantity="129", organismQuantityType="biomassG". For applications of the data, it is often extremely useful or even necessary to know how many individuals that the measure of biomass is based upon. 

That being said, and sticking to the topic of the tread: Terms describing temporal dimensions that technically can be captured in dwc:eventDate (e.g. dwc:year) are in my opinion technically redundant, but serves practical purposes as long as data aggregators such as GBIF does not recognize interval expressions in temporal dimensions, a common case, due to either uncertainty in underlying data source or sampling conducted with gear that samples over periods of time such as malaise traps (the inability of dwc to distinguish between such cases in expressing temporal intervals is a different but still an annoying issue). A hack to this is to publish data with dwc:eventDate representing the correct interval and including dwc:year and other time measures to let the data aggregator ingest temporal information from this.

**Comment by qgroom** [comment]
Yes, GBIF is still not handling valid ISO8601 date ranges, though your workaround only works if the data range is shorter than a year and all of mine are longer than a year. They are also automatically  populating the `dwc:year`, `dwc:month` & `dwc:day` with the information from the first date in the date range.

This is an issue for GBIF. I don't think the standard should have to support these errors.

Also, there is nothing stopping any database manager implementing a year field if they think is will be more efficient, but that is different from having it in the standard. 

Correct me if I'm wrong, but Darwin Core is an exchange standard to improve the interoperability of data. The addition of date derivatives and the lack of proper support for ISO8601 actually reduces interoperability.

**Comment by MattBlissett** [comment]
Fully supporting ISO8601 date ranges would be a significant change to our API.  We're working towards that.  There's some older discussion on https://github.com/gbif/gbif-api/issues/4 and https://github.com/gbif/gbif-api/issues/2, but the final implementation hasn't been decided.

As you say, we now automatically populate year/month/day using the start of a date range.  This was only introduced in October.

> A hack to this is to publish data with dwc:eventDate representing the correct interval and including dwc:year and other time measures to let the data aggregator ingest temporal information from this.

The ideal for GBIF now is having only `dwc:eventDate`. We can then derive the other fields from that. It's more complicated to decide what should happen when `dwc:eventDate` conflicts with one or more of `dwc:year`, `dwc:month` and `dwc:day`.

We don't do much at all with `startDayOfYear` or `endDayOfYear`; neither interpretation nor allowing searching on the field.

I think I would recommend people publishing data to GBIF not to populate `year`, `month`, `day`,  `startDayOfYear` or `endDayOfYear`, but instead rely on GBIF to derive them for searching and analysis.

**Comment by qgroom** [comment]
Hi @MattBlissett you don't say it explicitly, but it seems from what you say that you would support the deprecation of `dwc:year`, `startDayOfYear` & `endDayOfYear`. It looks like that is the direction GBIF is going in. If you recommend people not to complete these fields the deprecation is a mechanism to do this.
Perhaps the best move is to do this once 8601 date ranges have been implemented properly on GBIF.

**Comment by tucotuco** [comment]
> However, they're useful as search terms and we've no intention to change that. They're probably also useful for users who can do basic analysis without needing to parse all the dates.

This is exactly why they were adopted in the first place. It is useful to have solid definitions for them, but probably less useful to expect a data publisher to produce them when they can be derived rigorously from other primary data. Given their value as search terms, I would not recommend trying to deprecate them.

**Comment by tucotuco** [comment]
This issue was proposed as a set of questions, which seem to have been answered.
