### ISSUE TITLE
dwc:month definition not rigorously correct.

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#229]
Currently, the definition says, "The ordinal month in which the Event occurred." Ordinal means, for example ('1st', '2nd', etc.). That is not the intent, nor is it how anyone is populating the field. The definition should be, "The integer month on which the Event occurred." This definition would match the pattern used for dwc:day. As this is not functionally a semantic change and would have no impact on published data, I would consider it an erratum that can be fixed without community vetting.

**Comment by peterdesmet** [comment]
Ok for me.

**Comment by baskaufs** [comment]
Agreed

**Comment by qgroom** [comment]
There seems general agreement that this issue can be fixed, but it has not been implemented. What needs to be done to get this changed. Do we need further approval of the DwC Maintenance Group or can we just fix it?

**Comment by baskaufs** [comment]
Looking at [Section 3.2](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#32-errata) on Errata in the VMS, I think in this case falls into the category where the maintenance group should make the change and send an email to TDWG-CONTENT informing the community of the change.  @tucotuco @peterdesmet and I are in agreement and are core members of the maintenance group.  Others are presumably watching the repo and have not spoken up.  So I would take that to be consensus of the maintenance group.

The only question is whether there are other changes that should be bundled with this one, since it will trigger a new version of the [term](https://github.com/tdwg/rs.tdwg.org/blob/master/terms-versions/terms-versions.csv), [term list](https://github.com/tdwg/rs.tdwg.org/blob/master/term-lists-versions/term-lists-versions.csv), and [vocabulary](https://github.com/tdwg/rs.tdwg.org/blob/master/vocabularies-versions/vocabularies-versions.csv).  If so, we'd want to update the version records for all of the changes at once.  

The last version I have for DwC is 2015-03-27.  Have there been any other version-triggering changes since then?  If so they should probably all be recorded in a new version release.

**Comment by baskaufs** [comment]
Fixed in 2020-08-12 version of DwC
