### ISSUE TITLE
Request of new terms (typeLocality, verbatimTypeLocality)

### ISSUE THREAD

**Issue by Archilegt** [tdwg/dwc#280]
Hi all,
I want to add new fields to Myriatrix (http://myriatrix.myspecies.info/), with the corresponding "machine names" in the internal database. I was checking the DwC Quick Reference Guide for Taxon class terms allowing me to share type locality information, so that I could apply consistent Drupal/Scratchpads machine names. I found no terms like typeLocality and verbatimTypeLocality, so I submit these to your consideration. The term "verbatimTypeLocality" could be a string used to register the type locality information as published. The term "typeLocality" could also be a string (at least for now), with the interpreted version of the type locality. For species-rank taxa under the ZooCode, those terms would need to be coupled to an additional term, stating which kind of types are considered, for example, if the type locality is based on a holotype or on a neotype. I do not recommend reusing the Identification class term typeStatus, but a different term, like basedOnType or similar.
If those terms are finally created, I would be most grateful if someone with Drupal skills could help with adding them to the Myriatrix database export process, so that the information could be shared to aggregators.
Cheers,
Charlie

**Comment by tucotuco** [comment]
Hi @Archilegt, 

This request involves the creation of a new term or terms, thus, in accordance with the [Vocabulary Maintenance Standard (VMS)](https://www.tdwg.org/standards/vms/) Section 3 it requires a full review, a public commentary, ratification if warranted, and then implementation. 

We are at the stage in the process where we have to demonstrate that the three main requirements for moving forward a change request are met. From the VMS Section 3.1:

> Because the primary purpose of TDWG vocabularies is to facilitate data sharing, it is necessary to show that multiple parties will benefit from the change. As such, it is a minimum requirement that two independent entities indicate that they desire the change (the **demand** requirement). Additionally, it is required that there is a consensus within the community that the proposed change will accomplish the desired outcome (the **efficacy** requirement), and that making the change will not adversely affect the interoperability of existing implementations that depend on the stability of the vocabulary (the **stability** requirement).

Before the proposal goes to public review, the demand requirement has to be demonstrated. It is the burden of those proposing to make this case. It has not been made explicit so far. In order to facilitate assessment, it is essential that the complete proposal be made explicit as well. Have a look at the  the [Guidelines for contributing](https://github.com/tdwg/dwc/blob/master/.github/CONTRIBUTING.md) and the following issues as examples of how to do that:

https://github.com/tdwg/dwc/issues/237
https://github.com/tdwg/dwc/issues/246

With the two prerequisites described above satisfied, the proposal can move forward. The Darwin Core Maintenance Interest Group has its open [annual review meeting](https://www.tdwg.org/conferences/2020/working-sessions/#itg02:%20darwin%20core%20maintenance%20group) on [2020-09-23T14:30+00:00](https://www.tdwg.org/conferences/2020/working-sessions-schedule/), during which we will attempt to make progress on as many open issues as possible. The more mature a justification is, the further along we can move a proposal.

**Comment by nielsklazenga** [comment]
Type locality means nothing to botanists. It has never been on the radar of the TNC.

I think having this term in Darwin Core will cause problems for linked data and conflict with the Darwin Core RDF Guide. Taxa have names, names have type specimens and type specimens, like any specimens, are collected somewhere, so there are several layers that are being skipped.

**Comment by tucotuco** [comment]
Closing for lack of evidence of demand.
