### ISSUE TITLE
Machine readable documents for terms don't contain any information

### ISSUE THREAD

**Issue by zerocrates** [tdwg/dwc#286]
The Turtle, RDF/XML, and JSON-LD files linked from http://rs.tdwg.org/dwc/terms.htm all have nearly no data in them. There are some hasPart/isPartOf relationships, but the types, labels, comments, etc. of the terms are all not included.

Is this: a) intended, b) a bug, or c) an unimplemented feature? Or am I possibly missing something?

**Comment by baskaufs** [comment]
That is as intended. One question is "what should you get when you dereference the IRI of a resource?" One probably shouldn't necessarily expect to get triples that are linked to the nodes that are linked to the subject resource (i.e. expect to get triples about terms that are linked to term lists). That often happens in the case where RDF is served via a static ontology document document, but these triples are generated dynamically from a database. So you get triples about the term list `http://rs.tdwg.org/dwc/terms/` that link it to the terms on the list, but if you want the triples about those terms, you would need to dereference their IRIs to get that information. 

It's a bit misleading that when you dereference http://rs.tdwg.org/dwc/terms/ in a browser you get more than just info on the term list. That was more just a way to make it possible for humans to see a whole term list including the terms rather than having to look up each term by clicking on a link. Presumably a script wouldn't get "tired" of traversing links in the same way, so that's why the machine-readable metadata is more limited.

Although a core idea of Linked Data is that a client could "follow its nose" by discovering linked IRIs and then dereferencing them, as a practical matter, it's a pretty inefficient way to get the whole data set. You can actually get dumps of larger sets of triples by dereferencing IRIs like `http://rs.tdwg.org/dump/terms`and requesting RDF content-types. That particular IRI will basically get you all of the data about the `dwc:` term list and all of its terms. 

If you are wondering how you would have ever known that, check out the landing page for the TDWG rs.tdwg.org GitHub repo. [Section 3.4](https://github.com/tdwg/rs.tdwg.org#directories-machine-readable) explains how the TDWG RDF Data Catalog is organized and how you can determine all of the dump URLs. By retrieving all of the dumps, you can bulk load any or all of the machine-readable metadata into a triplestore or read it into an application. There's a Python script [here](https://github.com/tdwg/rs.tdwg.org/blob/master/index/database-triple-loader.py) that will load all of the data into triplestore using SPARQL UPDATE. For example, the entire TDWG dataset is loaded by that script into the `http://rs.tdwg.org/` graph at the endpoint https://sparql.vanderbilt.edu/sparql .

If you are interested in more details, I'd recommend reading three blog posts I've written on the subject: [one about accessing TDWG metadata by dereferencing the IRIs directly via content negotiation](http://baskauf.blogspot.com/2019/04/understanding-tdwg-standards.html), [one about accessing via SPARQL](http://baskauf.blogspot.com/2019/04/understanding-tdwg-standards_7.html), and [one about accessing via the data catalog dumps](http://baskauf.blogspot.com/2019/04/understanding-tdwg-standards_24.html).

Thanks for the question and I'm glad you are exploring the metadata!
