### ISSUE TITLE
Change term - dcterms:modified

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#294]
## Change term

* Submitter: John Wieczorek
* Justification (why is this change necessary?): The recommended specification for dates has been deprecated.
* Proponents (who needs this change): Everyone

Proposed new attributes of the term:

* Usage comments (recommendations regarding content, etc.): 
"Recommended best practice is to use a date that conforms to ISO 8601-1:2019."

**Comment by tucotuco** [comment]
This is correct in the Darwin Core term list document (https://dwc.tdwg.org/list/#dcterms_modified), but seems not to have been propagated to the Quick Reference Guide (https://dwc.tdwg.org/terms/#dcterms:modified)

**Comment by baskaufs** [comment]
I will take a look at this. It may be that if it is actually in the usage field, the usage field isn't supported in the QRG. But my memory is rusty.

**Comment by baskaufs** [comment]
There must be some problem in the script that builds the `term_versions.csv` file because its wrong there as well. I will track it down.

**Comment by baskaufs** [comment]
This is a tricky one. From a conceptual viewpoint, it is not clear how we are handling versioning in borrowed Dublin Core terms. Supposedly, we have updated the metadata for a particular version of a Dublin Core term, but we can't actually do that - we are not DCMI. What we are actually doing is updating the TDWG usage guidelines for Dublin Core terms, but currently DwC does not support the skos:scopeNote property for usage notes as it is used in Audubon Core with borrowed terms. 

The whole system for handling versions of borrowed terms is not well thought out and that's why this particular thing got broken. The rs.tdwg.org processing scripts don't really handle versioning for borrowed terms because it is so unclear how it should be done in various circumstances. In the case of borrowed Dublin Core terms, the illegitimate updating of term versions has to be done manually, which is why it got missed in this case.

Anyway, it is fixed for now, but this situation will continue to arise any time we change the metadata for Dublin Core terms. We aren't actually accurately reflecting the DCMI guidelines anyway - compare our guidelines for dc:language with https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/elements/1.1/language . But that is a problem for another day...

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/commit/bf50cfcf0b43638924496ee20e3518e6d41949f7 and https://github.com/tdwg/dwc/commit/74c7a4244120acac455c2fb8020831bb41afeb5c
