### ISSUE TITLE
Darwin Core schema is not recognized by 3M

### ISSUE THREAD

**Issue by earnaud** [tdwg/dwc#304]
As I was trying to create a mapping from EML to DwC using Mapping Memory Manager (https://isl.ics.forth.gr/3M/), it happened the DwC schema was not recognized, while EML one was. Also, I did not understand which .xsd file was the "main" file for DwC schema.

I don't really know if the issue occurs from the tool or from your .xsd files. I am trying to get in touch with 3M maintainers to solve the issue.

**Comment by earnaud** [comment]
https://github.com/isl/Mapping-Memory-Manager/issues/1

**Comment by tucotuco** [comment]
Hi @earnaud I am not sure I understand what your ultimate use case is, but it seems odd to try to map from EML to DwC. We use EML in the context of a Darwin Core archive to capture the information about the primary data in the dataset in the archive, while the primary data are in Darwin Core. The two share some concepts, such as license, so that the individual records do not lose this important information when they are aggregated with data from other datasets. If you can explain more about what you eventually hope to, I might be able to make further recommendations.

**Comment by earnaud** [comment]
Hi @tucotuco ,

the concern here is that my colleagues and I are using slightly different standards among our different projects. It would be great for us to have a mapping tool / resource to convert files from EML to DwC (and vice versa) with losing the least information as possible. For this, the 3M tool seemed to be an excellent way to compare schemas, but as the issue in their repo revealed it, it actually seems not.

**Comment by tucotuco** [comment]
Hi @earnaud I am still missing something conceptually. Can you share an example?

**Comment by timrobertson100** [comment]
I just stumbled across this old issue. 

Did you ever create a mapping between your EML data file descriptors and DwC please @earnaud? If so, do you have an example? If this is no longer relevant can we close this issue? 

Thanks
