### ISSUE TITLE
Add event example to bibliographicCitation

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/dwc#311]
Currently, bibliographicCitation has two examples, one specimen example, one taxon example. In working to build an extension to the Event Core, I find it would be useful to provide people with an example for an event.
Could be:
'Rand, K.M., Logerwell, E.A. The first demersal trawl survey of benthic fish and invertebrates in the Beaufort Sea since the late 1970s. Polar Biol 34, 475–488 (2011). https://doi.org/10.1007/s00300-010-0900-2'

**Comment by as6699** [comment]
If this were the example, Paula, wouldn’t the proper format have the year listed right after the authors? Thus:

'Rand, K.M., Logerwell, E.A. (2011) The first demersal trawl survey of benthic fish and invertebrates in the Beaufort Sea since the late 1970s. Polar Biol 34, 475-488.   https://doi.org/10.1007/s00300-010-0900-2'

Annie Simpson
703-391-7950

On Jan 10, 2021, at 8:26 AM, Paula Zermoglio <notifications@github.com> wrote:

'Rand, K.M., Logerwell, E.A. The first demersal trawl survey of benthic fish and invertebrates in the Beaufort Sea since the late 1970s. Polar Biol 34, 475–488 (2011). https://doi.org/10.1007/s00300-010-0900-2'

**Comment by pzermoglio** [comment]
Thanks Annie @as6699, it would sound more natural to me too. However, that is the way recommended by the journal (see https://link.springer.com/article/10.1007%2Fs00300-010-0900-2#citeas). Given that there are several different formats for citations, I would think it's ok to cite as is suggested.

**Comment by as6699** [comment]
Understood. I do wish citations were more consistent, but at least it’s all there.

Annie Simpson

On Jan 10, 2021, at 9:22 PM, Paula Zermoglio <notifications@github.com> wrote:

﻿

Thanks Annie @as6699<https://github.com/as6699>, it would sound more natural to me too. However, that is the way recommended by the journal (see https://link.springer.com/article/10.1007%2Fs00300-010-0900-2#citeas). Given that there are several different formats for citations, I would think it's ok to cite as is suggested.

**Comment by tucotuco** [comment]
Added to the change request for Issue #336, closing this one.
