### ISSUE TITLE
Quick Term Guide hard to find

### ISSUE THREAD

**Issue by mdoering** [tdwg/dwc#312]
I am still not used to the move of the DwC Quick Reference Guide.

I used to be able to access it here from what I for years considered the main DwC URL:
http://rs.tdwg.org/dwc/

Now there is no link and rather hard to read technical information only.
Why has this been moved to a new subdomain https://dwc.tdwg.org/terms/ ?

The github homepage seems to be the only place this document is linked from.

Btw, the [DwC Homepage](https://dwc.tdwg.org) has a markdown link not rendered.

**Comment by baskaufs** [comment]
@mdoering The issue here is that in the past there was not a lot of consistency in the meaning of IRI patterns in the rs.tdwg.org subdomain. In the process of trying to make all of the standards-related metadata available through IRI dereferencing, I had to establish consistent IRI patterns. See the [pattern summary here](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#2nd-level-iris-denoting-vocabularies) for details. 

In every possible case, I tried to preserve the existing "permanent URLs" for legacy documents (e.g. the DwC XML guide, etc.). However, in several cases, there were URLs that were in use that conflicted with the hierarchical patterns described via the link above. <http://rs.tdwg.org/dwc/> apparently was one of them that I wasn't aware of -- <http://rs.tdwg.org/dwc/terms/> actually seemed to be in much more common use for the QRG, hence the big notification on the dereferenced page that users should change their bookmarks.

One problem is that the QRG is actually outside of the standard. Therefore it has not necessarily conformed to the Standards Documentation Specification that requires standards documents to have a header section that clearly indicates the permanent URL of the document. As a non-standards document, the QRG does not have a permanent URL in the rs.tdwg.org namespace that conforms to the rs.tdwg.org IRI patterns. Therefore, it is not included the "official" [spreadsheet that controls the redirection of documents](https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs.csv) for that namespace. 

The idea behind the "permanent URLs" for standards documents are that they would not change when content delivery systems change. But being outside that system the QRG just has its current URL ,https://dwc.tdwg.org/terms/> which is as permanent as we can keep it. If we are making some kind of commitment to that URL, it might be worthwhile in the QRG somewhere to tell people that this is the URL that they should cite and bookmark.

Pinging @peterdesmet @tucotuco @timrobertson100

**Comment by tucotuco** [comment]
I think there is value in commiting to the URL and agree that it is
"worthwhile in the QRG somewhere to tell people that this is the URL that
they should cite and bookmark."

**Comment by baskaufs** [comment]
Set as a task in #313
