### ISSUE TITLE
Change term - samplingProtocol

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/dwc#322]
## Change term

* Submitter: Paula Zermoglio @pzermoglio
* Justification (why is this change necessary?): To accommodate "summary" Events in which the specific protocols can not be attributed to specific Occurrences.
* Proponents (who needs this change): Humboldt Core Task Group (representing multiple independent stakeholders)

Current Term definition: https://dwc.tdwg.org/terms/#dwc:samplingProtocol

Proposed new attributes of the term:

* Term name (in lowerCamelCase): samplingProtocol
* Organized in Class (e.g. Location, Taxon): Event
* Definition of the term: **The names of, references to, or descriptions of the methods or protocols used during an Event.**
* Usage comments (recommendations regarding content, etc.): **Recommended best practice is describe an Event with no more than one sampling protocol. In the case of a summary Event with multiple protocols, in which a specific protocol can not be attributed to specific Occurrences, the recommended best practice is to separate the values in a list with space vertical bar space ( | ).**
* Examples: `UV light trap`, `mist net`, `bottom trawl`, **`ad hoc observation | point count`**, `Penguins from space: faecal stains reveal the location of emperor penguin colonies, https://doi.org/10.1111/j.1466-8238.2009.00467.x`, `Takats et al. 2001. Guidelines for Nocturnal Owl Monitoring in North America. Beaverhill Bird Observatory and Bird Studies Canada, Edmonton, Alberta. 32 pp., http://www.bsc-eoc.org/download/Owl.pdf`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/samplingProtocol-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Gathering/Method

Currently [dwc:samplingProtocol](http://rs.tdwg.org/dwc/terms/samplingProtocol) defined as:
> The name of, reference to, or description of the method or protocol used during an Event.

and with no comments associated.

Depending on how granular the reported event is, there may be more than one protocol to cite. 
Suggestion would be to tweak definition slightly to:
> The **names** of, **references** to, or **descriptions** of the **methods** or **protocols** used during an Event.

and to **add a comment** on how to separate multiple values, like: "If multiple values applicable, separate the values in a list with space vertical bar space ( | )."

**Comment by tucotuco** [comment]
I think this would go against the intention that an event would be the distinct application of a protocol at a place and time. If I understand what you are proposing, it is to cover a compilation case where an Event covers all the things that happened in a potentially extended place and time, to group things. What is gained by this over just having one Event at a place and time per protocol?

**Comment by robgur** [comment]
It may be the case that many occurrences are collected by multiple methods
over a range of time (a field biologist does pitfall and malaise trapping
at a site, for example), and are bundled into a single described "event"
e.g. the outcome of a multiple trap methods reported as a single list of
occurrences (or abundances).   While in theory it would be great each
occurrence was related to the sampling method that generated it, that isn't
always the case and it seems reasonable to allow aggregated reporting.

**Comment by tucotuco** [comment]
If that is really needed, then I would urge not to promote that practice by relaxing the existing term.

**Comment by pzermoglio** [comment]
@tucotuco 
Event is currently defined as:
   >An action that occurs at some location during some time.

Not necessarily to do with the protocol to carry out that action, right? 
You could be as granular as you want and define your action as, for example:
  - just "collect", and you could separately qualify that action with 
    - "using X and Y methods" in a 1-1 way or 
    - "using X method"+"using Y method" in a 1-many way 

or
  - specifically "collect with X method". 

So Event is already pretty relaxed, I don't see what change would be needed.

**Comment by tucotuco** [comment]
If you have an Event, and one of its properties is samplingProtocol, and
samplingProtocol is defined as singular, then any two different
samplingProtocols at a place and time necessarily constitute distinct
Events. Relaxing samplingProtocol in order to allow multiple protocols
necessarily relaxes Event, since samplingProtocol is one of its properties.
The change is theoretically possible, but it requires a semantic change,
and that is cause for public review.

**Comment by albenson-usgs** [comment]
In Rob's example above I'm wondering why you wouldn't have a parentEvent describing the whole thing and then events under that parentEvent that describe the different sampling techniques. Eg. parentEvent: Insect sampling through time, event: pitfall trapping, event: malaise trapping with their respective samplingProtocol.

**Comment by stanblum** [comment]
I think the key here is whether or not the results of the collecting events have been pooled so that which material came from which method is unknown. Back when Walter Berendsohn was asking for feedback on an early version of ABCD, the model stated that a collecting [=gathering] event could take place at one to many localities.  My comment was along the lines of: "That's crazy. Who does that? And even if collectors pool stuff from multiple localities, do we really want to accommodate bad practice?"  I think the ultimate resolution was to broaden the concept of a locality (e.g., site C = site A + site B). The resulting knowledge would be that a single organism could have come from either A or B.  In the same way, a mixed method could include two methods, e.g., a bulk sample containing specimens collected by malaise and pitfall traps.

**Comment by deepreef** [comment]
So... there's a bunch of things to unpack here.  First:

@tucotuco :
> I think this would go against the intention that an event would be the distinct application of a protocol at a place and time. 

And
> If you have an Event, and one of its properties is samplingProtocol, and samplingProtocol is defined as singular, then any two different samplingProtocols at a place and time necessarily constitute distinct Events. Relaxing samplingProtocol in order to allow multiple protocols necessarily relaxes Event, since samplingProtocol is one of its properties.

I don't think that's right. As already commented by @pzermoglio, the definition of an[ `Event` in DwC](https://dwc.tdwg.org/terms/#event) is: "An action that occurs at some location during some time." Yes, you could argue that "action" could be implied to be a singular `samplingProtocol`; but you could also interpret "action" more generally as "extracting organisms from nature". I've always defined 'Event' in my data modelling as: [Event=Location+Time].  But John's comments above seem to extend that to be [Event=Location+Time+Protocol]. 

In our fish collection, we have many specimens where the collection method is something like "Rotenone and Spear". This could be interpreted at the level of the `Event`, meaning that some of the specimens taken during the even were collected with rotenone, and others were collected with spear. But it could also be interpreted literally at the level of specimen (e.g., at a rotenone station, the fish got disoriented enough that Jack Randall was able to spear it; both methods played a role).  We have many similar records indicated as "Quinaldine and hand net". So I think there are legitimate examples of multiple protocols applied to a single specimen. Of course, we could define a distinct `samplingProtocol` as something like "speared while under the influence of rotenone", but I can imagine queries where I want to know all the specimens that were collected with the aid of a spear (because they might be damaged), separately from all the specimens that were potentially exposed to rotenone (for some biochemical reason), so that sort of thing seems easier to accommodate if I could set `samplingProtocol` to be "Rotenone|Spear"

And while I'm at it...

I agree with @stanblum that a single `Event` should be defined as the intersection of a *single* Location and a time.  But the caveat is that the example of "site C = site A + site B", implying that a single specimen could be from A or B but not both, has similar applications to the "time" component.  The statement of a single date implies "sometime within the range of 00:00 and 23:59 on that date".  "April 1980" implies "sometime between 1 April 1980 and 30 April 1980".  However, we also have to deal with cases of "either 4 April 1980 or 11 April 1980", in cases when a collecting team went out on two consecutive dates, and combined the specimens from both outings into a single event.  The distinction between a date range and one of two dates is similar to the issue with two discrete localities.

@albenson-usgs , in reference to the example from @robgur :

> In Rob's example above I'm wondering why you wouldn't have a parentEvent describing the whole thing and then events under that parentEvent that describe the different sampling techniques. Eg. parentEvent: Insect sampling through time, event: pitfall trapping, event: malaise trapping with their respective samplingProtocol.

I definitely support hierarchical events, so this is certainly one approach to accommodating these kinds of situations. But I'm not sure that solves the issue, because the `Event` instanced referenced by `parentEventID` still would need to represent multiple `samplingProtocol` values.

**Comment by albenson-usgs** [comment]
@deepreef I was thinking something like this
parentEventID    |    eventID                      |     decimalLatitude    |   decimalLongitude   |    eventDate      |     samplingProtocol
             NA         |     insects_1                   |            42.36              |            -23.22             |    2020-08-12    |             NA
     insects_1        |  insects_1_malaise_1    |              NA                |               NA               |        NA             |        malaise trap
     insects_1        |  insects_1_pitfall_1       |              NA                |               NA               |        NA             |        pitfall trap

Although admittedly this won't help much if everything is being pooled before this process like in Stan's example.

**Comment by deepreef** [comment]
@albenson-usgs : OK, thanks! That makes sense.  So specimens where it's uncertain whether the `samplingProtocol` was malaise trap or pitfall trap, would be linked to `eventID`:insects_1, with no explicit value for `samplingProtocol`; but an analysis of the "child" events for insects_1 would reveal that it was one of the two.  Is that the idea?  If so, the informatician & data modeler in me likes it!  But from a practical perspective, I wonder how normal it would be to analyze the child events of an indicated event to interpret the "A or B" `samplingProtocol` correctly.

Also, in most parent-child relationship, properties of the of the child are assumed to be inherited from the parent; but in this case, properties of the parent would be inferred from the set of properties of the children.  In our implementation, we already do that with event dates (i.e., when not explicitly indicated, we infer the date range of the parent event to be the min an max values indicated in the set of child events; same for other things like depth range and scope/extent of locality).  So I can also see this extending to `samplingProtocol` as well.

Definitely food for thought!

**Comment by tucotuco** [comment]
>  From @deepreef I definitely support hierarchical events, so this is certainly one approach to accommodating these kinds of situations. But I'm not sure that solves the issue, because the `Event` instanced referenced by `parentEventID` still would need to represent multiple `samplingProtocol` values.

Or none...

> From @albenson-usgs I was thinking something like this
> parentEventID | eventID | decimalLatitude | decimalLongitude | eventDate | samplingProtocol
> NA | insects_1 | 42.36 | -23.22 | 2020-08-12 | NA
> insects_1 | insects_1_malaise_1 | NA | NA | NA | malaise trap
> insects_1 | insects_1_pitfall_1 | NA | NA | NA | pitfall trap

Exactly.

> Although admittedly this won't help much if everything is being pooled before this process like in Stan's example.

And exactly. Perhaps a compromise solution is to recommend against pooling protocols if possible (and describe how with the  example from @albenson-usgs for both Event and Occurrence perspectives), but to support it (and describe how with the original proposal by @pzermoglio). In any case, I would run this one through public review. I have changed the title of the issue and prepended a templated term change request to the original comment so as not to have to make a separate issue and relate it to the discussion in this one.

**Comment by baskaufs** [comment]
`dwc:samplingProtocol` does have a `dwciri:` analog. I believe that the following Usage comment should be added to make an analogous clarification:

> Usage comments (recommendations regarding content, etc.): Recommended best practice is describe an Event with no more than one sampling protocol. In the case of a summary Event in which a specific protocol can not be attributed to specific Occurrences, the recommended best practice is to repeat the property for each IRI that denotes a different sampling protocol that applies to the Occurrence.

This is similar to how we handle other terms where the literal value term separates multiple values with pipes, i.e. allow the `dwciri:` property to be repeatable. But check the wording to make sure this makes sense. (For reference, see the last paragraph of section 1.4.3 of the [RDF guide](https://dwc.tdwg.org/rdf/)

**Comment by dr-shorthair** [comment]
FWIW this appears to be closely related to [sosa:usedProcedure](https://www.w3.org/TR/vocab-ssn/#SOSAusedProcedure) when used in the context of an act of sampling [sosa:Sampling](https://www.w3.org/TR/vocab-ssn/#SOSASampling)

**Comment by tucotuco** [comment]
Done.
