### ISSUE TITLE
New Term - vitality

### ISSUE THREAD

**Issue by sophiathirza** [tdwg/dwc#363]
## New term

* Submitter: Sophia Ratcliffe

* Efficacy Justification (why is this term necessary?): There is a requirement that species records express whether the organism was dead or alive at the time of the observation or collection. Currently no such explicit term exists in Darwin Core.

* Demand Justification (name at least two organizations that independently need this term):  
    - NBN Trust
    - Ocean Biodiversity Information System (OBIS)
    - The Field Museum
    - Global Genome Biodiversity Network (GGBN)

* Stability Justification (what concerns are there that this might affect existing implementations?):  None

* Implications for dwciri: namespace (does this change affect a dwciri term version)?: The term `dwciri:vitality` will be created simultaneously with the term in the main DwC namespace: `dwc:vitality`.

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes):  `vitality`
* Organized in Class (e.g., Occurrence, Event, Location, Taxon):  `Occurrence`
* Definition of the term (normative): An indication of whether the organism was alive or dead at the time of collection or observation
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use a controlled vocabulary. Intended to be used with records having a dwc:basisOfRecord of `PreservedSpecimen`, `MaterialSample`, or `HumanObservation`.
* Examples (not normative, for the `dwc:` namespace term only): `alive`, `dead`, `mixedLot`, `uncertain`, `notAssessed`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): I was not able to find an equivalent term

NOTE:
The Darwin Core Maintenance Group has assessed that more work is required to have a consensus on a controlled vocabulary, so that part of this proposal did not pass the 2023-02-12 public review cycle. Because of this, and in an effort to make the term available as soon as possible, the following originally proposed Comments section has be replaced by what is seen in the final proposal, above:
* Usage comments (recommendations regarding content, etc., not normative): Recommended best practice is to use a term from the controlled vocabulary intended to be used with this term, listed at <http://rs.tdwg.org/dwc/doc/vit/> Generally intended to be used with a `dwc:basisOfRecord` of `PreservedSpecimen`, `MaterialSample`, or `HumanObservation`.

The Vitality Controlled Vocabulary to be used as values for this term can be viewed [here](https://github.com/tdwg/rs.tdwg.org/blob/vitality/process/page_build_scripts/vitality.md) (note: the URL listed in the comments will not dereference until after ratification). `dwc:vitality` will use the controlled value string for the appropriate concept in this vocabulary as its value. `dwciri:vitality` will use the unabbreviated term IRI as its value.

**Comment by sophiathirza** [comment]
We will submit a proposal for a causeOfDeath extension in due course.

**Comment by TimAPearce** [comment]
Because shells persist for thousands to millions of years after the death of the animal who formed it, whether the specimen was collected alive can be important to understand the distribution in time and space of LIVING individuals of species.

**Comment by jannvendetti** [comment]
I'd reiterate TimAPearce: if we know whether the specimen was collected alive or dead and can add that information to the specimen record, that can help researchers using the data understand more about the biology of the organism.

**Comment by rbieler** [comment]
I support this in the strongest possible way.  Because of the long-term persistence of calcareous skeletal material (e.g., molluscan shells) these may have been dead for decades or even centuries when collected.  Such data are obviously suspect when used in discussions/maps of recent changes in faunal distributions.  We need to find a meaningful way to flag live/dead-collected specimens and have that distinction readily piped to relevant data aggregators.

**Comment by Paul-Larson** [comment]
Plus one here, others have already made the case well enough.

**Comment by DMNHverts** [comment]
Thanks to everyone for their work on this- I support it

**Comment by gparosenberg** [comment]
Other organizations that need this term include iNaturalist, which has an attribute of "Alive" or "Dead" and the Academy of Natural Sciences of Philadelphia (ANSP). Currently more than 3.5 million observations in iNaturalist are annotated for this attribute, including 125,000 for mollusks. The malacology database as ANSP also supports the live dead distinction, which has been made for 56,000 samples.

**Comment by fmrdelapena** [comment]
The distinction between live/dead is a key problem for the entire molluscan community because it affects the usability/fidelity of mollusk-based biodiversity records. Dead-collected shells can be hundreds of years old; therefore, their records 
would not be useful in addressing short-term questions related to climate change or range extensions.

**Comment by debpaul** [comment]
@gparosenberg wrote:

> Other organizations that need this term include iNaturalist, which has an attribute of "Alive" or "Dead" and the Academy of Natural Sciences of Philadelphia (ANSP). Currently more than 3.5 million observations in iNaturalist are annotated for this attribute, including 125,000 for mollusks. The malacology database as ANSP also supports the live dead distinction, which has been made for 56,000 samples.

I  note that iNaturalist also has "evidence of recent life" to convey something was alive not too long ago (as opposed to a shell that's been there for who knows how long which could be more of a "relict" idea).

**Comment by debpaul** [comment]
@rbieler @fmrdelapena what other collections (outside mollusks) would / could use this term meaningfully? As you put it so nicely in a use case Robin, known it is/was recently alive (until collected anyway) then the data is fit for use in addressing range extension assessment (for example). Are there other collections, that could use this similarly? (Doesn't really seem to work for herbarium specimens -- they are all (I think?) alive at time of collection by default).  But would this distinction work for other collection types that can then support a research purpose?

**Comment by rbieler** [comment]
@debpaul This would apply to many of the calcareous skeletons in our (proverbial) closets of "dry" collections -- corals, bryozoans, brachiopods, foraminiferans, etc.

**Comment by ewommack** [comment]
> unable to determine | The functional metabolism of the organism is not possible to determine
-- | --


I do wonder about the use of this term. It seems like unknown would cover this, and adding it in will lead to confusion between when a collection chooses to use one or the other term.

**Comment by ekools** [comment]
Since the vitality field (or fields) can often be determined after collection, I would add another term: "**not yet determined**."   It seems to me, because this is a new field (or fields), the first entry for all existing dry preserved records would be "not yet determined". In practice, I don't see that every specimen within a lot will be evaluated. In my mind, the question is, Is there at least one specimen in the lot that was collected live?  Conceivably a specimen lot could have specimens that were live collected, dead collected, "not recorded" and "unable to determine"  I'm having a hard time seeing what the fields will be here. Is there one Vitality field with the above terms and they are check boxes? I don't think that is very informative for Queries/Searches. Are the fields dead, alive and not recorded? And the alive and dead fields have values of True, False and unable to determine and not yet determined?  I think that is a lot of checkboxes. Or, because the primary question is whether or not there is at least one live specimen, there are two fields only: Alive and Not recorded. Where the alive field is T, F, not yet determined or unable to determine. That seems simplest of all. A field that indicates at least one specimen was collected live. My apologies if this is dealing too specific for this thread. I'm just trying to see how this is going to look in practice.

**Comment by rbieler** [comment]
@ekools For our Thematic Collections Network project (Eastern Seaboard mollusks), we have agreed - at the collections end - to record the following for each lot: 

- live [when collected]
- dead [when collected]
- live + dead [= mixed lot]
- uncertain [= can’t currently tell after visual inspection; use comments if needed]
- not assessed [or empty entry, depending on database system used]

Because of the wide variety of database systems involved in our project (EMu, Specify, Arctos, Filemaker, etc.) we are still working on the collections-level implementation of the above.  We understand that our desired collection-level distinction might be too detailed to pass on to aggregators, so we could readily combine them into a smaller number of items (e.g., live [including mixed lots] / dead [only] / unknown -- or  live / dead/ unable to determine / unknown) once such an option exists

**Comment by RRabeler** [comment]
@debpaul:  I agree - not sure this term would find much use in the herbarium community.

**Comment by ewommack** [comment]
I'm fascinated and also a little worried if I come across a vertebrate object that would use either of the:

> live + dead [= mixed lot]

> uncertain [= can’t currently tell after visual inspection; use comments if needed]

I'm sure IACUC would have words with me...

**Comment by ekools** [comment]
Thank you, @rbieler  I think in practice we would focus on whether or not there is a live collected specimen, eliminating the need to evaluate each specimen. So, would lean towards your last example and eliminate the live + dead field as this could be indicated by a True Value in both the live and dead collected fields. The field Not Recorded is interesting because it indicates the evaluation was made after collection. Fun stuff. Thanks!

**Comment by tmcelrath** [comment]
I support the use of this term as currently defined. It would be useful in the entomological collections community, as we mostly collected specimens alive and kill them, but occasionally find "preservable" specimens that died recently, but it would be useful to have this term in order to indicate that it was not alive at time of collection, and therefore should not have bearing on things like phenology, etc ...

**Comment by fmrdelapena** [comment]
@debpaul -- In some cases entomological collections could use this term.  I myself have collected quite a bit of material where the specimen was found dead.  Currently, we use "hand collected" as the collection method and "found dead" as the detail.  Since many arthropod's life cycles are annual its would be easier to assume its "age".   On the other hand, if a season or two has passed, a dead insect specimen would most likely have deteriorated from the elements and wouldn't be worth collecting anyway.

**Comment by ewommack** [comment]
For vertebrate collections you may want to talk to eBird, iNaturalist, and the Zoo community. They will have the largest sample sets currently that may get listed as Live. The majority of vertebrate museum specimens currently are going to be dead. This may change as we work with more behavioral researchers, but the full vouchered specimens are still going to come into our collections already expired.

**Comment by RoGinz** [comment]
All of the vitality qualities possible in different kinds of collections need not be specified as a list item for a
"vitality" classification to carry important specimen information, viz. the example noted above, of mollusk shells 
surviving their owners and possibly being transported far from their origin.  Additionally, the collection of living
specimens has different legal and provenance implications depending on the date of collection.  A researcher 
wishing to use data can sort by vitality category to eliminate, for example in the above two cases, specimens
of dubious geographic origin or specimens illegally collected.  The finer points of vitality relevant to particular
types of collections might be added as subsections, or preserved in narrative fields.  OP's proposal seems sound.

**Comment by gparosenberg** [comment]
I don't have a set of cause of death terms, but I've been able to score more than 60,000 records in our malacology collection database for vitality based on information in the records. If cause of death were also recorded when known, that would increase the usefulness of the data. In our Eastern Seaboard TCN, we are interested in whether an observation gives evidence that a species lived at a site on a particular date. If, for example, one observes a seagull carrying a clam and dropping it on rocks, the observation gives evidence that the clam lives in the area. If the fragments are collected, however, they would be scored as dead. Our project has experimented with two fields, "vitality" and "means of inference", but not a "cause of death" field.

"Cause of death" would presumably refer to death other than that caused by preservation of the specimen in a collection. If one has a collection that includes living items, perhaps that could be indicated here as "still living", to distinguish current vitality from vitality at time of collection.

On iNaturalist, the instructions are that if something is moribund, it should be scored as dead. Whether that is appropriate depends on the question being asked. When I see whelk egg cases washed up on a beach, scoring them as dead seems appropriate, although further investigation might reveal that some of the egg cases contain juvenile snails that are still alive. Nonetheless, they would almost certainly die soon, because they are stranded on the beach. Maybe it would be better to score them as "cannot be determined", which is one of the values allowed by iNaturalist. Even that depends on context. The person who made the observation would have more information than a subsequent person evaluating the image to decide if it should be scored as live or dead.

I'd advocate having a controlled vocabulary that allows considerable granularity, because different researchers have different questions. We have tested "live", "possibly live", "fresh dead", "dead", "long dead", "subfossil", and "fossil". The latter two turned out to be useful only as "means of inference". If the record stated a specimen was subfossil or fossil, it can be scored as dead. How long something has been dead is a different axis.

"Possibly live" versus "fresh dead" allowed us to preserve distinctions. If we have bivalves that are paired (valves still attached by ligament), it might be that they were collected alive and killed by the collector, or they might have been found dead on the beach, still paired. If the collector recorded this information, the scoring as live or dead is easy. If the information was not recorded, it can be difficult to infer, although it is sometimes possible, for example if bits of tissue adhere to the shell, one could infer that it was live-collected. A later observer could choose "possibly live", when they are unable to make the distinction or don't have time to do it.  Someone using the data could then decide if they want to include "fresh dead" and "possibly live" observations, depending on the question they were asking.

Some of our lots have a mixture-some specimens live-collected and some dead-collected. For these it would be useful to have an option for "live and dead". I prefer this to two separate flags, one for live and one for dead, because if both were checked, that would immediately raise the question of whether there was an error in data entry.

Looking at our means of inference field, for items flagged as fresh dead, I see several items relevant to a list of causes of death: eaten by a bird or fish, dropped on road by seagull, drilled by a muricid, naticid or octopus, found drowned

Best wishes,
Gary

**Comment by baskaufs** [comment]
In consultation with the Task Group convener and in preparation for this going to public comment, I have formalized the Task Group's recommended values into a formal controlled vocabulary that can be viewed here: <https://github.com/tdwg/rs.tdwg.org/blob/vitality/process/page_build_scripts/vitality.md>.

As a consequence, I edited the original term proposal to match the style of other terms that have officially designated controlled vocabularies. I also edited the `examples` section (for the dwc: namespace analog) to match the controlled value strings as listed in the controlled vocabulary. I also made a note (consistent with existing DwC policy) that a `dwciri:` term would be minted simultaneously with the `dwc:` term and that the term IRIs from the controlled vocabulary would be used as its values.

**Comment by tucotuco** [comment]
This issue has accumulated massive support, but there remain unresolved issues with respect to consensus, at least as captured in this particular issue. Does the Task Group have a recommendation that addresses all of the concerns expressed here?

**Comment by albenson-usgs** [comment]
I thought the same thing as Quentin.

**Comment by jhpoelen** [comment]
In re-reading the thread, I still wonder why we're not re-using the physiological state from PATO (see https://github.com/tdwg/dwc/issues/363#issuecomment-949961320).

Especially after reading the examples described in:

https://github.com/tdwg/rs.tdwg.org/blob/vitality/process/page_build_scripts/vitality.md



Label | dead
-- | --
Definition | The **state** where the organism has irreversible loss of functional metabolism at the time that the observation or collection was made


Label | alive
-- | --
Definition | The **state** where the organism has functional metabolism at the time that the observation or collection was made

To me, vitality seems to suggest some kind of quantitative score between alive (e.g., 10) and dead (e.g., 1). and I think describing a physiological state may be a little more nuanced than that.

Inventing new terms is easy, but keeping them is . . . time intensive! (e.g., https://github.com/oborel/obo-relations/issues/368 - a new term request is still ongoing after first being proposed in 2020). So, I favor re-use of existing terms.

my 2 cents.

**Comment by tucotuco** [comment]
I realize that the public review is for the proposal as it currently stands, and that there were no explicit objections during the public commentary period. However, there are comments from prior to the public review for which it is not apparent that they were ever addressed, and the outcomes if they were is not in evidence. Here are the specific comments in question:

https://github.com/tdwg/dwc/issues/363#issuecomment-949961320
https://github.com/tdwg/dwc/issues/363#issuecomment-953631051 and 
https://github.com/tdwg/dwc/issues/363#issuecomment-954153258. There was some discussion about the name vitality, with "viability" "physiologicalState" as options. The latter (as "pato:physiological state") seems to cover the same concepts and is used in several ontologies. A poll proposed was mentioned, but no results of that poll were shared.

Others were discussions about vocabulary values (whose final proposed values can be seen at https://github.com/tdwg/rs.tdwg.org/blob/vitality/process/page_build_scripts/vitality.md.

Many of the comments about the proposed vocabulary seem to have been addressed, but not all, at least in this issue. For example,
https://github.com/tdwg/dwc/issues/363#issuecomment-970569151

It would be good to know if these comments were addressed anywhere, and what the outcome was.

**Comment by ekools** [comment]
All of these fields pertain to data from the observer/collector.  Why not include the Inferred Data in the same Vitality Scheme ?

**Comment by qgroom** [comment]
> I've seen a similar term described at "physiological state", with terms from ontologies like PATO:
> 
> term name	term IRI
> dead	http://purl.obolibrary.org/obo/PATO_0001422
> alive	http://purl.obolibrary.org/obo/PATO_0001421
> Examples in GloBI would be something like:
> 
> Jane saw a cat eating a dead mouse.

The PATO definitions of dead and alive are quite similar, though they are under PATO viability which is different from the definition of `vitality`.

`viability`
> An organismal quality inhering in a bearer or a population by virtue of the _bearer's disposition to survive and develop normally_ or the number of surviving individuals in a given population.

`vitality`
> An indication of whether the organism was alive or dead at the time of collection or observation.

I'm not sure the difference in definition of the parent matters, but other siblings of `viability` would not be suitable, such as immortal, lethal and semi-lethal.

> How did you come to the name `vitality`?
After a great deal of toing and froing and compromising ;-)

**Comment by gparosenberg** [comment]
In the Eastern Seaboard TCN, we have recommended adding fields to record means of inference of the vitality status. Also, because mollusk collections usually catalogue by lots rather than individual specimens, we've found that it might speed assessment to allow additional values beyond "live" dead" and"uncertain". Ech of the items below can be mapped to one of the three main values .

Live and dead: Both live and dead collected specimens are in the lot. Maps to "live"
Possibly live: at least one specimen might have been live collected. Indicates that the specimen is in good enough condition that it might have been alive when collected. Maps to "Can't be determined"
Fresh dead: no specimen in the lot was live collected, but at least one is known to have been fresh dead (e.g., valves of bivalves still attached by ligament). Maps to "Dead".
Best wishes,
Gary

**Comment by qgroom** [comment]
> For the definition of "uncertain" "The functional metabolism of the organism was not possible to determine at the time that the observation or collection was made" would be changed to read "The functional metabolism of the organism (at the time of observation or collection) is not possible to determine." 

> The term "not assessed", defined as "The functional metabolism of the organism was not recorded at the time that the observation or collection was made" would be changed to "The functional metabolism of the organism has not yet been determined or assessed."

> I think it is the order of the wording that is throwing me off. For alive, it is easier for me if "The state where the organism has functional metabolism at the time that the observation or collection was made" reads "The state where the organism (at the time of observation or collection) had functional metabolism.

I don't think anyone would have a problem with those amendments.

The vocabulary is only a recommendation and non-normative, which is why I can't really understand why this causes a block to vitality be accepted, particularly when there is such obvious and immediate demand.

**Comment by tucotuco** [comment]
The issue is not blocked. It just requires consensus. Consensus has not been achieved for the reasons described [here](https://github.com/tdwg/dwc/issues/363#issuecomment-1490320342). 

Examples of vocabulary terms would be non-normative, but given [this comment](https://github.com/tdwg/dwc/issues/363#issuecomment-1271719854), a formal vocabulary (normative) is also being proposed. Consensus has not been demonstrated on the controlled vocabulary.

**Comment by qgroom** [comment]
But a consensus was formed by the task group. You will understand my frustration when we could have dispensed with a whole bunch of task group meetings if the consensus we built there doesn't really count for anything.

The comments by @gparosenberg, @jhpoelen  and @ekools don't even seem to conflict with the suggested controlled vocabulary.

**Comment by albenson-usgs** [comment]
I agree with Quentin. There are 24 thumbs up and many people saying they would use this term once available. I guess I'm confused how three mild suggestions that are not even outright disagreements means there is not consensus. How long do we have available to provide responses from the task group to what's been outlined [here](https://github.com/tdwg/dwc/issues/363#issuecomment-1490320342) to still get this term approved during this public commentary period? I have a dataset that cannot be shared until this term is available and I would really like to move that one forward if I can.

**Comment by fmjjones** [comment]
I think a bit of explanation would help this issue. The goal of the task group is to define terms for the question "How did it die?" We are discussing many other terms with their own vocabularies to expand this set of terms. The goal with the term Vitality is to expedite the acceptance of a single term the for which the community has expressed an immediate need. Once we have the basic question of if an organism was dead or live at the time of observation/collection, we can expand the terms for use by, among others GGBN.  Physiological State is a much broader term then what we are hoping to achieve with Vitality.

**Comment by baskaufs** [comment]
If the problem is only with the controlled vocabulary itself, it seems to me that the `vitality` term itself could be adopted with additional work on the controlled vocabulary later. We have plenty of terms in Darwin Core for which a controlled vocabulary is not (yet) available. I haven't paid close enough attention to the discussion of the controlled vocabulary to know what the issue is with it, but if it is an issue with missing values, they can be added later. If it's an issue with non-critical proposed values, they could be removed, leaving the critical ones. 

It is frustrating to me when the perfect becomes the enemy of the good. That seems to be a common problem with Darwin Core proposals. It leads to frustration and cynicism on the part of people who put in a lot of work on a proposal and we risk losing the participation of those people in future efforts if they feel the time they've expended doesn't pay off.

This proposed term has been languishing for a long time and there's huge demand for it. If there is a way to cut out or fix the aspects of the propose that lack consensus, we should do it and get at least the term itself adopted.

**Comment by sophiathirza** [comment]
I am sorry - I realised that I didn't add the notes from the TDWG 2021 working session, where we had a poll on the name of the term.

I've uploaded the group chat and meeting notes here: https://github.com/tdwg/how-did-it-die/tree/main/meetings/TDWG%202021%20WG%20session

The options for the poll were: 1. vitality, 2. viability and 3. physiological state. Nine people voted (there were only 12 in the session), results:

vitality 5  
viability 1 
physiological state 3

It was agreed to continue with vitality as the term name and to add the term 'mixed' to indicate collection lots of both live and dead organisms.

**Comment by sophiathirza** [comment]
> For the definition of "uncertain" "The functional metabolism of the organism was not possible to determine at the time that the observation or collection was made" would be changed to read "The functional metabolism of the organism (at the time of observation or collection) is not possible to determine."
> 
> The term "not assessed", defined as "The functional metabolism of the organism was not recorded at the time that the observation or collection was made" would be changed to "The functional metabolism of the organism has not yet been determined or assessed."
> 
> I think it is the order of the wording that is throwing me off. For alive, it is easier for me if "The state where the organism has functional metabolism at the time that the observation or collection was made" reads "The state where the organism (at the time of observation or collection) had functional metabolism.

I am happy for the definitions to change, as described above.

> I also think that persons using data available in the aggregators are going to find "Evidence of Recent Life" and/or "Recently Alive" (=fresh dead) of immense value and we want to include them in the definitions. The term aestivating may also be included too. I'm not sure.

We did discuss including dormant in the vocabulary, but the organism is alive - and we wanted to keep the term as simple as possible for the most practical use. 

The date of death is going to be covered in the cause of death extension proposal and the group agreed that 'recently alive' or 'freshly dead' could be covered by the date of death. If there is a use case of including it in the vocabulary then we can consider it again, but we should be clear what recent or fresh means.

**Comment by tucotuco** [comment]
Thanks @sophiathirza for the Task Group background information. Looking through the thread it seems that the justification for the choice of term name has been met. All other open discussion is about the controlled vocabulary. It also seems there is clear and immediate use for the term even without the associated formal controlled vocabulary. I'll change the status of this issue to "Ready for Executive Review" and start to prepare the entire package. 

A new issue should be created to move forward with the controlled vocabulary, and should reference this issue as background and the source for remaining issues that need to be resolved. 

Thank you everyone for your efforts and patience. Progress!

**Comment by tucotuco** [comment]
Huzzah!

**Comment by qgroom** [comment]
For those of you interested in a causeOfDeath term I have added a specific term request here https://github.com/tdwg/dwc/issues/521
Please give it some support with comments and a 👍
