### ISSUE TITLE
taxonID required even without extensions - please update guidelines

### ISSUE THREAD

**Issue by CecSve** [tdwg/dwc#415]
A GBIF checklist publisher noticed an issue with the [guidelines](https://dwc.tdwg.org/text/) stating that: 

>  If extensions are being used, each record in the core data MUST have a unique identifier. The field for this identifier MUST be specified in an explicit <id> field in order to associate extension records with the core record.

In some cases, publisher might have records in their databases for uncertain names (in this case potential synonym) that cannot be resolved, and for which they cannot provide a taxonID. However, they get an error when the try to publish their dataset stating that every record should have a taxonID, even though they do not use any extensions. 

Perhaps the cited text should should be:

>  Each record in the core data MUST have a unique identifier. The field for this identifier MUST be specified in an explicit <id> field in order to associate extension records with the core record.

to avoid confusion?

**Comment by timrobertson100** [comment]
Thanks for reporting this @CecSve. I'm sorry, I overlooked the original notification and only just see this when @tucotuco assigned me.

I think in the time that has passed since this was opened, we've discussed and identified that this relates specifically to the implementation choices GBIF took in the IPT; namely that it enforces `taxonID` to be the same as the core record `id`, and that it must be present and unique even when no extensions are used if I understand correctly.

The intention behind the Text Guidelines when written was less restrictive aiming to accommodate the use of Darwin Core in lots of spreadsheet data. It's reasonable that someone may design a spreadsheet where `taxonID` is repeated across rows, depending on their need.

Given that this seems to be a GBIF-specific problem and that it introduces a restriction that hasn't been present before, my feeling is this would be better handled in the GBIF publishing guidelines, rather than the DwC Text Guide.

What do you think, please?

**Comment by CecSve** [comment]
Sorry for my late reply and thank you for the clarification. I agree, it is more fitting in the publishing guidelines.
