### ISSUE TITLE
.ttl file does not provide list of terms

### ISSUE THREAD

**Issue by henrietteharmse** [tdwg/dwc#435]
To use dwc in an ontology I tried to import it from http://rs.tdwg.org/version/dwc/2021-07-15.ttl. However, on inspection I noted that this is not an ontology(?) that can be opened by typical ontology tools like Protege or ROBOT. See screenshot below of dwc on the left vs Dublin core on the right. For dwc terms cannot be read but for Dublin core it can when opened in Protege.  

![image](https://user-images.githubusercontent.com/32327979/219392551-9a9e69bc-8c0d-433d-943d-10832039d9ff.png)

Or is this a case me looking at wrong .ttl file? Then please point me to correct one.

**Comment by baskaufs** [comment]
Because TDWG vocabularies borrow terms from other vocabularies, TDWG vocabulary structure is a bit more complicated than a simple vocabulary that contains terms defined in a single namespace. See [this diagram](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#1-metadata-model-for-tdwg-standards) of the structure and the [machine-readable section of the Standards Documentation Specification](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#4-machine-readable-documents) for details.

The thing that would correspond to what many people might consider a "vocabulary" is what we refer to as a "term list". Each term list contains all of the terms from a particular namespace that is included in a vocabulary. For example, the term list denoted by <http://rs.tdwg.org/dwc/terms/> contains all of the terms included in the main Darwin Core namespace `dwc:`. If you dereference that IRI and request Turtle or RDF/XML, you should get RDF for each term in that namespace. I haven't tried loading it into Protege, but those triples can successfully be loaded into a triplestore.

A semantic application could follow its nose and traverse the graph, loading resources as it discovered them via links. However, a more practical approach is to acquire dumps of all of the triples associated with "datasets" (sensu the W3C DCAT specification). There is more about how to do that [here](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#34-retrieving-machine-readable-metadata-from-the-datasets). You can retrieve a full, machine-readable list of the available datasets by dereferencing <http://rs.tdwg.org/index> requesting Turtle or RDF/XML, or just use the URLs <http://rs.tdwg.org/index.ttl> or <http://rs.tdwg.org/index.rdf>. 

In any case, the organization of the machine-readable TDWG data is really designed to facilitate loading the metadata into a triplestore and not an application like Protege. However, if you want to examine the granular parts of the vocabularies, you probably can do that by loading the Turtle or RDF/XML for individual term lists into Protege.

If this isn't clear, I'm happy to answer followup questions.

**Comment by henrietteharmse** [comment]
This complexity of the dwc is not unique. Importing of ontologies into other ontologies is done often as can be seen in the many of ontologies on the [Ontology Lookup Service](http://www.ebi.ac.uk/ols) and even in DCAT that you mentioned can be opened in Protege of which I provide a screenshot below:

![image](https://user-images.githubusercontent.com/32327979/219415008-93a8bcef-71ba-4130-b03e-9f9b763ec880.png)


I have looked at http://rs.tdwg.org/index.ttl and http://rs.tdwg.org/index.rdf before opening this issue. I was hoping to import dwc into another ontology to build on top of, which these links do not help with. But, I think based on your answer, this was never the intended use of dwc. I initially thought this was an accidental oversight but now see this may be intentional.

**Comment by baskaufs** [comment]
Well, the design of TDWG vocabularies is to first create a "bag of terms" with clear labels and definitions, but without entailment-generating assertions or extensive datatyping requirements. That should allow for a variety of uses, from spreadsheets to ontology building. Other more restrictive layers could theoretically be built on top of this basic layer. So far that hasn't yet been done officially within the TDWG standards process, but has been done within the community, most notably with the [Biological Collections Ontology (BCO)](https://obofoundry.org/ontology/bco). 

Frankly, the use of these machine-readable metadata has been small compared to the overall use of the TDWG vocabularies to facilitate data uploading and aggregation. For that reason, the machine-readable aspects of the metadata have not been worked on extensively. As things currently stand, the RDF representations are generated as a by-product of the processing that takes place when the vocabularies are changed or added to. If new use cases could be clearly defined for the machine readable metadata, those processes could probably be modified to account for them. Up to this point, the main use case has been to be able to load all of the triples into a triplestore for querying.

**Comment by tucotuco** [comment]
Closing as "answered".
