### ISSUE TITLE
Please change smooth scrolling to jump scrolling on DwC terms pages

### ISSUE THREAD

**Issue by Mesibov** [tdwg/dwc#440]
The new Quick Reference Guide and List of Darwin Core Terms pages use smooth scrolling instead of jump scrolling. Smooth scrolling is fine for short pages but unnecessary and an annoying animation for these two very long pages.

The culprit is in main.css at line 66. To enable jump scrolling just change "scroll-behavior:smooth" to "scroll-behavior:auto". I do this every time I open these pages (to stop myself being annoyed) but it would be an easier change at the server end.

Many thanks.

**Comment by peterdesmet** [comment]
Thanks for reporting, I will look into this.

**Comment by peterdesmet** [comment]
Smooth scrolling is now disabled for _all_ sites and pages that use the new TDWG theme. It would be overly complicated to only disable it for long pages or selected sites.

What has changed: clicking an anchor in the side navigation will now _jump_ to that section on the page, rather than visually _scrolling_ to that section. This is similar to how it was before and to [Dublin Core](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) pages, so I hope that is fine for everyone.

The change will automatically be applied when a site is rebuild (on a commit to `main`/`master`). As a result, you will not see it everywhere yet. I did trigger a rebuild for the Darwin Core website, so the change is already implemented on https://dwc.tdwg.org/terms/ (you might want to Cmd+Shift+R to clear cache).
