### ISSUE TITLE
Template for non-normative usage documents

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#444]
There are terms for which the constraints of a text string without new lines in a CSV are insufficient to captured the guidance needed to use the term. One example of this is the new term verbatimLabel (see https://github.com/tdwg/dwc/issues/32). This has also come up recently for the Humboldt Extension Task Group. Some existing very long comments or comments that span terms might be other good candidates for this.

In such cases it will be useful to include links to additional documents in the usage comments. It would be nice if such documents had a template so that there is some consistency to their presentation.

**Comment by peterdesmet** [comment]
Would it help to make use of json rather than csv as the main normative file?

**Comment by tucotuco** [comment]
That still wouldn't be a sufficient solution in some cases and would create a huge obstacle for some.

**Comment by tucotuco** [comment]
One option might be as [wiki pages](https://github.com/tdwg/dwc-qa/wiki) in the Darwin Core Q&A repository. Looking for ideas so that we can implement this for the [verbatimLabel term](https://github.com/tdwg/dwc/issues/32), for which there is immediate need as we seek ratification.

**Comment by MattBlissett** [comment]
I think Markdown (or similar) files within the repository would be better, as they're then versioned and take the same pull requests etc as the main repository.  GitHub's interface for editing Wiki pages and Markdown files is very similar.

**Comment by debpaul** [comment]
I don't get this yet. Am i understanding that we need to be more explicit that each verbatimLabel text blob (for a given herbarium label or entomology label, etc) for a specimen/object must be in an expected format like .csv or .txt or .md? Is that what you mean that you want a) examples and b) explicit in the **Usage** comments?

**Comment by timrobertson100** [comment]
> I don't get this yet

@debpaul, we use simple CSV files to hold the master record for the TDWG standards themselves, from which we produce various views, like the web page and RDF etc. Until now "examples" have been simple strings that go in the comments column. We're now seeing more expressive examples and this issue is about how to manage those for producing our own TDWG views. 

The idea on this thread is to link to a separate page that provides the examples e.g. in `verbatimLabel` it would say 

> Please see [this link](https://gist.github.com/timrobertson100/1405a9849a74bde3f7bc4ce7efd61115) for examples of use.

However...

> There are terms for which the constraints of a text string without new lines in a CSV are insufficient to captured the guidance needed to use the term.

It should be possible to encode new lines within the CSV cells with appropriate quoting. Are there bugs in our scripts that generate the views, or is it just the nuisance factor?

**Comment by baskaufs** [comment]
I agree that having multiple examples outside of the basic term metadata is a good idea. I think there are a technical question that needs to be answered about exactly where the examples should live and how they should be formated.

Will the document contain any normative guidance or will it only contain examples? 

1. If there is any normative guidance, then the document should be included as part of the standard, follow the SDS guidelines, delineate which sections are normative and which are not, and have a permanent URL in the rs.tdwg.org subdomain. It would look like what we are doing here in Humboldt Extension: <https://github.com/tdwg/hc/blob/main/docs/inclusive/index.md> (will eventually dereference from http://rs.tdwg.org/eco/doc/inclusive/). 

2. If it only contains examples and is likely to be edited and changed a lot, then I would not include the document as part of the standard, give it a URL in the dwc.tdwg.org subsomain (similar to the Quick Reference Guide) and use whatever formatting is desired. It would be similar to the RegionsOfInterest recipes document (<https://github.com/tdwg/ac/blob/master/roi-recipes.md>), which doesn't have a URL in the ac.tdwg.org namespace, but probably should. We should try to keep the URL stable so that we can link to it from the actual term comments.

3. There is a third option: include it as a document in the standard, follow the SDS formatting rules, give it a URL in the rs.tdwg.org subdomain, and declare that all parts of it are non-normative. I think this would be appropriate of the examples are unlikely to change frequently. As an official standards document, changing it would have to follow the VMS process, but it would be easier to change since all of it is non-normative.

The issue with using a URL like http://rs.tdwg.org/dwc/examples/verbatimLable_example is that in order for URLs in the rs.tdwg.org subdomain to dereference, they need to follow [a particular URL pattern](https://github.com/tdwg/rs.tdwg.org#2nd-level-iris-denoting-standards-documents) or else special rule needs to be written in the server script to handle the idiosyncratic URL (similar to what we had to do with the legacy URLs for the DwC text, XML, and RDF guides). If we did put it in rs.tdwg.org, then it should probably have a permanent URL with a form like http://rs.tdwg.org/dwc/doc/verbatimLabel_example/ .

There isn't any "rule" that says documents outside of standards can't have permanent URLs in the rs.tdwg.org subdomain, but the point of minting document URLs there is to also provide a bunch of machine readable metadata that among other things describes what standard they are part of. Currently [all of the documents that have those URLs](https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs.csv) are officially part of some standard, so this would be something new that doesn't fit in with current metadata management practices.

**Comment by debpaul** [comment]
> We need to decide on this to move forward with the current DwC release.
> 
> I propose to create `/dwc/docs/examples/verbatimLabel_example.md` with the content found [here](https://gist.github.com/timrobertson100/1405a9849a74bde3f7bc4ce7efd61115) and the scripts adapted to reference that absolutely (not relatively) as http://rs.tdwg.org/dwc/examples/verbatimLabel_example.md from the documentation.

@timrobertson100 please note (I'd edit if I could). In your gist example ...
the first example is from _labels affixed to a pinned insect specimen_ (not a vial).

**Comment by tucotuco** [comment]
> Thank you very much @baskaufs - I think I follow at least some of that.
> 
> I think I'm proposing something akin to your option 2. and would be happy to follow the ROI as an example. Would that work for you @tucotuco? I can knock up a template for examples in DwC, provide the verbatimLabel one, and check with Peter that it renders correctly in the site build.

Yes, that works for me. I had always seen this as purely non-normative content - examples - moved to a place where they would actually work. We have to remember that is all the document can do going forward unless we switch into one of the other modes @baskaufs mentioned.

**Comment by timrobertson100** [comment]
The PR for this is [here](https://github.com/tdwg/dwc/pull/481)

**Comment by tucotuco** [comment]
Template examples document that can be used as a model for the future incorporated at http://rs.tdwg.org/dwc/examples/verbatimLabel_example.md.
