### ISSUE TITLE
Consistency in references to namespaces

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#446]
We are inconsistent in how we reference terms both within and across namespaces, with mixes of using namespace abbreviations and not using them. My hope for consistency is to include namespace abbreviations in contexts (definitions, comments) where a term that is mentioned is from another namespace, and not to do so when the term is in the same namespace. Looking for support or alternatives to this idea.

**Comment by peterdesmet** [comment]
I support either always writing with namespace (makes it very clear we're talking about a term):

> A categorical description of the extent to which the georeference has been verified to represent the best possible spatial description for the <strong>dwc:</strong>Location of the <strong>dwc:</strong>Occurrence.
> 
> `cf. var. oxyadenia` (for `Quercus agrifolia cf. var. oxyadenia` with accompanying values `Quercus` in <strong>dwc:</strong>genus, `agrifolia` in <strong>dwc:</strong>specificEpithet, `oxyadenia` in <strong>dwc:</strong>infraspecificEpithet, and `var.` in <strong>dwc:</strong>taxonRank)

... or adding the namespace if different that the current one.

**Comment by baskaufs** [comment]
I think we should always use the namespaces if we are actually referencing a particular term. Including the namespace makes the reference a globally unique identifier for the term because it abbreviates the term IRI. This allows us to distinguish between colloquial use of a term, and a specific reference to a term. We've seen this in discussions of "dwc:Organism", which has a different technical meaning from what we typically understand "organism" to mean. 

I realize this is annoying, but particularly since we made the choice to create the IRI analog namespace (dwciri:) and use the same local name, we are just asking for trouble when we leave the namespace off. I'm starting to regret that decision now -- in AC, Bob Morris made the choice to use different local names in the same namespace (`ac:commenter` and `ac:commenterLiteral` for example) for the analogs and I think that has ended up to be less problematic. But hindsight is 20-20...

**Comment by tucotuco** [comment]
I have made similar issues for Chronometric Age and Humboldt extensions. DwC work on this should also cover the controlled vocabularies for degreeOfEstablishment, establishmentMeans, and pathway.

**Comment by tucotuco** [comment]
Addressed in https://github.com/tdwg/dwc/commit/265f9c5ed4efdbec8824aa6dd6bc9b2cf8a3427c.
