### ISSUE TITLE
Fix examples for most classes

### ISSUE THREAD

**Issue by tucotuco** [tdwg/dwc#499]
In term_versions.csv, classes that should have been unaffected by MaterialEntity-related changes no longer have backticks and semi-colons separating distinct examples

**Comment by baskaufs** [comment]
I don't see this. I'm looking at the most recent version and they are all there:
![image](https://github.com/tdwg/dwc/assets/5765781/5d852d8d-5f4b-41b2-ace8-112e176aa8cb)

**Comment by baskaufs** [comment]
Have you viewed the QRG in a private browser window or cleared your cache? These are all rendering fine for me on my browser.

**Comment by tucotuco** [comment]
Yes, both. Evidence for correct version is the updated date in QRG.

<img width="874" alt="image" src="https://github.com/tdwg/dwc/assets/462827/36dfc31b-cd96-49df-a152-dc1b448377b2">

**Comment by baskaufs** [comment]
Sorry, I misread "unaffected" as "affected". I will look into this...

**Comment by baskaufs** [comment]
OK, I have investigated and figured out what the problem is. Nothing was corrupted. We just never delineated the class examples. I verified this by looking at the term_versions.csv file at https://github.com/tdwg/dwc/blob/8e0c25e01ebdeff6a500b919b7486d0963d336f2/vocabulary/term_versions.csv, the version present after commit https://github.com/tdwg/dwc/commit/8e0c25e01ebdeff6a500b919b7486d0963d336f2, the one that closed https://github.com/tdwg/dwc/pull/443#issuecomment-1523257360 . I sorted by "recommended" status and rdf:type and here's what I saw:

![image](https://github.com/tdwg/dwc/assets/5765781/dfd8fbb8-d7e2-48b3-a542-c3c3a3356e03)

The properties were all done but the classes were not. You can see this on the previous version of the List of Terms: https://dwc.tdwg.org/list/2023-07-07 . The non-deprecated properties have the styling, the classes don't. It's a little harder to see in a previous commit of the QRG like https://github.com/tdwg/dwc/blob/5b671332c256e531269dfbcd147354db79ce51a3/docs/terms/index.md since it isn't styled, but look carefully at the classes and you'll see what I mean.

The other bit of evidence is that we actually created new term versions when we updated the example styling (even though technically we didn't have to do that. Notice that there aren't new versions of the class terms. We didn't update them.

I suppose this is something we should fix, but it wasn't fixed before and we managed to live with it. If we have time to fix it, maybe we should do it, but do we want it to block the new release?

**Comment by baskaufs** [comment]
@tucotuco Here's what I'm thinking. I think the simplest thing is to just create a new 2023-09-18 version of DwC with the class example formatting changes. With the scripting it's no big deal. I think that would be easier than trying to go back and insert the changes as a hack. That would also generate new term versions for the classes just like we did for the properties.

I'm pretty busy getting ready to be out of the office for a week, but if you would have time to put the metadata for the class terms with the fixed example formatting into a CSV with headers like https://github.com/tdwg/rs.tdwg.org/blob/master/process/dwc-revisions/dwc-revisions-2023-09-13/terms_2023-09-13.csv, I should be able to run the changes through the scripts and regenerate everything later today.

**Comment by tucotuco** [comment]
@baskaufs Hmm. Interesting. Thanks for the sleuthing. The fixes are straightforward. I can provide updated versions via a new folder in rs.tdwg.org/process/dwc_revisions if you agree.

**Comment by tucotuco** [comment]
@baskaufs [New folder](https://github.com/tdwg/rs.tdwg.org/commit/d5cbc70c964c8273d4866eaa9271b4719b1d9aaf) added.

**Comment by baskaufs** [comment]
@tucotuco Working on it. Noticing that all of the changed classes are going from "extension" to "simple". is that OK?

**Comment by tucotuco** [comment]
@baskaufs Yes, not just OK, essential. Not sure why or when they became extension. No need to know really.
