### ISSUE TITLE
multiple vernacular names for a taxon?

### ISSUE THREAD

**Issue by wouteraddink** [tdwg/dwc#503]
looking at https://dwc.tdwg.org/terms/#dwc:vernacularName it seems to allow for only one name, should it not allow for a list of names since one taxon can have multiple vernacular names?

**Comment by qgroom** [comment]
There is a DwC extension to add multiple vernacular names, and it allows for their language to be given. Otherwise you might end up with multiple names, but you don't know what languages they are in.
@matdillen used the extension in thise dataset https://www.gbif.org/dataset/a0b06e2e-287a-4687-8a6c-2c0cfb31c16d

**Comment by wouteraddink** [comment]
Aah yes, I forgot about that extension.
