### ISSUE TITLE
New Term - superfamily

### ISSUE THREAD

**Issue by ammatsun** [tdwg/dwc#65]
## New Term
Submitter: Andréa Matsunaga

Justification: Among animals (e.g., mollusks and tardigrades), individuals are classified in a taxonomic category, subordinate to an order and superior to a family. In order to effectively capture this more refined classification information, I recommend the addition of superfamily. iDigBio has evidence that multiple data providers have this level of information and would like to share it with the community. Absence of this term in the DwC standard hinders sharing of this level of taxonomic information especially when using tools such as IPT.

Definition: a taxonomic category subordinate to an order and superior to a family. According to ICZN article 29.2, the suffix -OIDEA is used for a superfamily name.

Comment: Examples "Achatinoidea", "Cerithioidea", "Helicoidea", "Hypsibioidea", "Valvatoidea", "Zonitoidea"

Refines:

Has Domain: http://rs.tdwg.org/dwc/terms/Taxon

Has Range:

Replaces:

ABCD 2.06: ScientificNameIdentified/HigherTaxon/HigherTaxonRank (enumeration value: superfamilia)

**Comment by peterdesmet** [comment]
This proposal needs more **evidence for demand** (see the [Vocabulary Maintenance Specification - Section 3.1](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#31-justifications-for-change)). Anybody who is interested in the adoption/change of this term, should comment with their use case below. If demand is not demonstrated by the next annual review of open proposals (late 2020), this proposal will be dismissed.

**Comment by nielsklazenga** [comment]
I am wondering what people do with these terms. For pretty much every use case I can think of `parentNameUsage` is more appropriate. Even if `parentNameUsage` cannot be delivered, I think `higherClassification` will be easier on the consumer, as they won't have to deal with all the missing or "incertae sedis" ranks.

The `kingdom` –`genus` terms were considered problematic in the Darwin Core RDF and treated as convenience terms in the Identification class. In order to "fix" the Darwin Core Taxon class and make it more suitable for exchanging linked data, they will have to be removed. I would certainly not add any extra ones.

Same goes for: #44, #45, #46 and #47.

**Comment by dhobern** [comment]
I certainly include superfamily and tribe in the columns for the datasets I share for insect families - these are enormously informative taxonomic ranks in the hyperspeciose insect orders. Not having these ranks would be like losing genus and order from classification in Mammalia. I would note that large numbers of iNaturalist observations are identified only to superfamily or tribe.
    
Niels is correct that we can (and perhaps should) normalise into a hierarchical model rather than relying on convenience terms, but these are two ranks that are very heavily used in entomology.

**Comment by mdoering** [comment]
All DwC terms for higher ranks are essential in the current GBIF implementation. You can only search occurrences or get metrics by those ranks. If we want to be able to search GBIF by tribe or superfamily we need to have the corresponding rank term in DwC. This might have to change in the long run to be more flexible, but that is what it is now and it won't be simple to change.

Superfamily has since the early days in Catalogue of Life been the only additional rank to the major Linnean ranks - it is important in many groups.

**Comment by tucotuco** [comment]
> I am wondering what people do with these terms. For pretty much every use case I can think of `parentNameUsage` is more appropriate. 

In a word, spreadsheet data - the most common use to date for Occurrences.

> Even if `parentNameUsage` cannot be delivered, I think `higherClassification` will be easier on the consumer, as they won't have to deal with all the missing or "incertae sedis" ranks.

> The `kingdom` –`genus` terms were considered problematic in the Darwin Core RDF and treated as convenience terms in the Identification class. In order to "fix" the Darwin Core Taxon class and make it more suitable for exchanging linked data, they will have to be removed. I would certainly not add any extra ones.

Nothing has to be removed from Darwin Core for a linked data solution. We just have to make sure that the appropriate terms for that realm are available. If there is a deficiency there., we can fix it, or rely on TCS2 for that case when it comes along.

> Same goes for: #44, #45, #46 and #47.

**Comment by tucotuco** [comment]
> I certainly include superfamily and tribe in the columns for the datasets I share for insect families - these are enormously informative taxonomic ranks in the hyperspeciose insect orders. Not having these ranks would be like losing genus and order from classification in Mammalia. I would note that large numbers of iNaturalist observations are identified only to superfamily or tribe.
> 
> Niels is correct that we can (and perhaps should) normalise into a hierarchical model rather than relying on convenience terms, but these are two ranks that are very heavily used in entomology.

If we can get support for the inclusion of this term from iNaturalist (or any other group needing to share these data), we will have demonstrated the evidence for demand.

**Comment by deepreef** [comment]
See my [comment on the issue](https://github.com/tdwg/dwc/issues/45) for the proposed new term `tribe`.

**Comment by DaveNicolson** [comment]
Sorry for cross-posting this... I was alerted to the discussions about proposed new ranks (superfamily, subfamily, tribe and subtribe), and thought it might be good to note that there is a fair amount of use of these ranks in ITIS, especially in Animalia. In that kingdom, here are the counts of the valid/accepted names at those ranks, as a quick data point:

rank_name	Animalia
Superfamily	577
Subfamily	2534
Tribe	1634
Subtribe	176

Clearly, some are in use more than others. I would argue that the superfamily level and subfamily level are not at all uncommon, particularly in some groups.
