### ISSUE TITLE
vegetation monitoring plots DwC

### ISSUE THREAD

**Issue by camiplata** [tdwg/dwc#98]
Dear colleagues,

At SiB Colombia we are standardizing a resource of vegetation plots that are going to be monitored for several years, the data includes both measurements of the event and the organisms.  So, we are currently discussing how to address this kind of data through the occurrenceCore and the new eventCore.

We propose to create  two related resources, the first describing the biotic and abiotic data of each plot (eventCore + meassurementOrFacts + relevé), and the second describing the organisms and it’s functional traits (occurrenceCore + meassurementOrFacts). The resources will be related through eventID and parentEventID. 

We would like to know  what do you think about this approach and if anyone is dealing with the same kind of data and how did you address this issue, or if we also will need to relate the resources through the resourceRelationship extension?

Looking forward for your assessment.

Best!

**Comment by peterdesmet** [comment]
Hi @camiplata, at [our institute](https://www.inbo.be/en), we also plan to publish vegetation plots using Darwin Core's event core, probably later this year. Since this is still unexplored territory, I think it would be a good idea to collaborate on this!

Copying @dimevil and @niconoe.

**Comment by camiplata** [comment]
That’s great @peterdesmet , in the following months we will be exploring the workflow I mentioned before. We will be looking forward to collaborate in this regard.
@nestorjal and @leobuitrago are in head of implementing this kind of data through [SiB Colombia](http://www.sibcolombia.net/)

**Comment by pieterprovoost** [comment]
At OBIS we are facing the same issue, i.e. how to have sample related as well as organism related parameters. Creating two related resources (one event core, the other occurrence core) is one of the options we are exploring. I'm very interested to see how others are dealing with this.

**Comment by nestorjal** [comment]
By the end of August we want to develop a sort of document/paper (we already have some data examples) to put our ideas about this issue together, whit that done any feedback or collaboration we'll be appreciated. Surely if we join efforts the outcome will be better, please tell me if you are interested.

**Comment by kbraak** [comment]
I just stumbled across this issue and wanted to update everyone that GBIF is promoting a new sampling event data model for vegetation plot data that uses a newly released [Relevé extension](http://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml).

A complete description of the data model including an example dataset can be found in this [recent blog post](http://gbif.blogspot.dk/2016/07/probably-turbovegs-best-kept-secret.html).

**Comment by nestorjal** [comment]
Thanks @kbraak, I'll check Turboveg. 

What do you think about this extension. it will be really helpful with measurements performed in a single individual (e.g. DAP, height, etc.) associated with a given event. I'm not sure about the implications with the Darwin Core star schema but so far is a good answer to some data (not published) that we are trying to transform in order to share.

http://tools.gbif.org/dwca-validator/extension.do?id=http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact

**Comment by tucotuco** [comment]
Hi folks,

I am in the process of cleaning up Darwin Core issues. This one looks like it may be complete. If not, I recommend moving it to the open forum for discussions about Darwin Core (tdwg-content@lists.tdwg.org), where it will have a wider audience. Since there is no particular Darwin Core issue here, I will mark it as 'wontfix' and close it.
